SET sql_mode='NO_BACKSLASH_ESCAPES';
CREATE TABLE user (
	id INT NOT NULL, 
	username VARCHAR(150) NOT NULL, 
	password_hash VARCHAR(128), 
	PRIMARY KEY (id), 
	UNIQUE (username)
);
INSERT INTO user VALUES(1,'sousuke0416','scrypt:32768:8:1$nLz4ZGyAUUHjZrf4$a047a5ea7571e11fed34baa472e1e36fe7a15c94b1b11a5271cbe9838db20e3b80bb4bc579b0a774b6f0ae1289b520eac18ac3d49e6ca7d12a79b47022876bae');
INSERT INTO user VALUES(2,'sumire2525','scrypt:32768:8:1$r7EwHWB7csZgDAhY$389ca6c9941a19cf583b48753c008230ca6c4de69f3c9435179f0a51ae2edc32ea9c4bf95ca48b245c4e17082f85e23134f0c8d7339a5a6f4573aeb10627b9d8');
INSERT INTO user VALUES(3,'87miya','scrypt:32768:8:1$iwPDNatCq9gmqD20$d0538fdccead1665ce6e258ecf451c557de6d06aa745030c0780b49e3db913c06155401fdd57d4c76c5ca6477b854bd3aaa1f0f941e7449dc2adb0a215e53c7d');
INSERT INTO user VALUES(4,'kajiken','scrypt:32768:8:1$FSwtDNn6NltRR1XH$86377d4eac73d50a2738fc2caec3fc77e28f8a82d570718261e478ed2e3cda2b80cc913dd1ce75a2284618c218699c6f60892b0c6006f47f8acf95594dd0cd2b');
INSERT INTO user VALUES(5,'ako','scrypt:32768:8:1$3Gdg6QgEBOu4Jyn7$a30a926f60573188f4d3855b13f09d84853a01adbcfe7a53ddc73c2aeb885f49e7b904d5855a5fbc1af029d50279d4ad47f8bc83d0c8b0ef749e8a4dd54b8b44');
INSERT INTO user VALUES(6,'shingo','scrypt:32768:8:1$TBfXENGYHHzSZJra$f83e528c0de6a70c4f2df5c95e1f7ce770c310184f3bd8ba4ae5f37be69e18ddb8c6579a1d37d32f08a9190c54cc847063c3a9eb7e28aeead636b1f094a55ec9');
INSERT INTO user VALUES(7,'KingKazuma','scrypt:32768:8:1$qdbgzii6s91cjcxI$73f01c6ee5895803ed2eeb3f29dc4c6581b39a05cfd93b971d424960e820861e179c0a233015c78576beb22ff6b41bc5df9eddc8dcf314ae9d2d546839b83773');
INSERT INTO user VALUES(8,'test_user1','scrypt:32768:8:1$a2UJqMpMWJD7m06g$d6ee25bfb0a445710ba628fa989f397734260e6c4f1b14be13d2c247ddda59f8487b95b497bcb2bc5eddc3c872db43917973ed08f4f325cdfedf93c5888326e4');
INSERT INTO user VALUES(9,'test_user2','scrypt:32768:8:1$A2Ahn3Jo4MS5GCEu$2fc233d0f6166d60f9f5acbd6f951681a9861b35c5f03fee06329d8333a534aa618312973951992667e2b49ba09f42e7acb62c4bdeb6ae1436153c560f73c111');
CREATE TABLE ranking (
	user_id INT NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	score INT NOT NULL, 
	playtime VARCHAR(100) NOT NULL, 
	PRIMARY KEY (user_id)
);
INSERT INTO ranking VALUES(1,'sousuke0416',100,'2024-07-30 02:46:28');
INSERT INTO ranking VALUES(2,'sumire2525',70,'2024-07-09 18:53:30');
INSERT INTO ranking VALUES(3,'87miya',100,'2024-08-02 15:27:28');
INSERT INTO ranking VALUES(4,'kajiken',40,'2024-07-10 12:03:09');
INSERT INTO ranking VALUES(5,'ako',90,'2024-08-08 17:46:08');
INSERT INTO ranking VALUES(6,'shingo',80,'2024-07-12 21:27:26');
INSERT INTO ranking VALUES(7,'KingKazuma',100,'2024-08-07 16:02:55');
INSERT INTO ranking VALUES(9,'test_user2',10,'2024-08-09 13:25:14');
CREATE TABLE all_kanji (
	kanji_id INT NOT NULL, 
	kanji VARCHAR(128), 
	kunyomi_roma VARCHAR(1024), 
	kunyomi_ja VARCHAR(1024), 
	onyomi_roma VARCHAR(1024), 
	onyomi_ja VARCHAR(1024), 
	PRIMARY KEY (kanji_id)
);
INSERT INTO all_kanji VALUES(1,'一','hito','ひと','ichi','イチ');
INSERT INTO all_kanji VALUES(2,'何','nani, nan','なに、なん','ka','カ');
INSERT INTO all_kanji VALUES(3,'七','nana, nano, nanatsu','なな、なの、ななつ','shichi','シチ');
INSERT INTO all_kanji VALUES(4,'飼','ka, kau','か、かう','shi','シ');
INSERT INTO all_kanji VALUES(5,'示','shime, shimesu','しめ、しめす','shi, ji','シ、ジ');
INSERT INTO all_kanji VALUES(6,'述','no, noberu','の、のべる','jutsu','ジュツ');
INSERT INTO all_kanji VALUES(7,'序','n/a','','jo','ジョ');
INSERT INTO all_kanji VALUES(8,'織','o, oru, ori','お、おる、おり','shoku, shiki','ショク、シキ');
INSERT INTO all_kanji VALUES(9,'税','n/a','','zei','ゼイ');
INSERT INTO all_kanji VALUES(10,'舌','shita','した','zetsu','ゼツ');
INSERT INTO all_kanji VALUES(11,'銭','zeni','ぜに','sen','セン');
INSERT INTO all_kanji VALUES(12,'祖','n/a','','so','ソ');
INSERT INTO all_kanji VALUES(13,'測','haka, hakaru','はか、はかる','soku','ソク');
INSERT INTO all_kanji VALUES(14,'八','ya, you, yattsu','や、よう、やっつ','hachi','ハチ');
INSERT INTO all_kanji VALUES(15,'属','n/a','','zoku','ゾク');
INSERT INTO all_kanji VALUES(16,'損','soko, sokoneru, sokonau','そこ、そこねる、そこなう','son','ソン');
INSERT INTO all_kanji VALUES(17,'退','shirizo, shirizoku, shirizokeru','しりぞ、しりぞく、しりぞける','tai','タイ');
INSERT INTO all_kanji VALUES(18,'銅','n/a','','dou','ドウ');
INSERT INTO all_kanji VALUES(19,'徳','n/a','','toku','トク');
INSERT INTO all_kanji VALUES(20,'犯','oka, okasu','おか、おかす','han','ハン');
INSERT INTO all_kanji VALUES(21,'版','n/a','','han','ハン');
INSERT INTO all_kanji VALUES(22,'俵','tawara','たわら','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(23,'婦','n/a','','fu','フ');
INSERT INTO all_kanji VALUES(24,'富','to, tomu, tomi','と、とむ、とみ','fu, fuu','フ、フウ');
INSERT INTO all_kanji VALUES(25,'九','kokono, kokonotsu','ここの、ここのつ','kyuu, ku','キュウ、ク');
INSERT INTO all_kanji VALUES(26,'武','n/a','','bu, mu','ブ、ム');
INSERT INTO all_kanji VALUES(27,'複','n/a','','fuku','フク');
INSERT INTO all_kanji VALUES(28,'墓','haka','はか','bo','ボ');
INSERT INTO all_kanji VALUES(29,'報','muku, mukui, mukuiru, mukuu','むく、むくい、むくいる、むくう','hou','ホウ');
INSERT INTO all_kanji VALUES(30,'防','fuse, fusegu','ふせ、ふせぐ','bou','ボウ');
INSERT INTO all_kanji VALUES(31,'貿','n/a','','bou','ボウ');
INSERT INTO all_kanji VALUES(32,'務','tsuto, tsutomeru, tsutomaru','つと、つとめる、つとまる','mu','ム');
INSERT INTO all_kanji VALUES(33,'綿','wata','わた','men','メン');
INSERT INTO all_kanji VALUES(34,'余','ama, amari, amaru, amasu','あま、あまり、あまる、あます','yo','ヨ');
INSERT INTO all_kanji VALUES(35,'略','n/a','','ryaku','リャク');
INSERT INTO all_kanji VALUES(36,'十','too, to','とお、と','juu','ジュウ');
INSERT INTO all_kanji VALUES(37,'領','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(38,'域','n/a','','iki','イキ');
INSERT INTO all_kanji VALUES(39,'宇','n/a','','u','ウ');
INSERT INTO all_kanji VALUES(40,'沿','so, sou','そ、そう','en','エン');
INSERT INTO all_kanji VALUES(41,'灰','hai','はい','kai','カイ');
INSERT INTO all_kanji VALUES(42,'閣','n/a','','kaku','カク');
INSERT INTO all_kanji VALUES(43,'割','wa, waru, wari, wareru, sa, saku','わ、わる、わり、われる、さ、さく','katsu','カツ');
INSERT INTO all_kanji VALUES(44,'株','kabu','かぶ','n/a','');
INSERT INTO all_kanji VALUES(45,'干','ho, hi, hosu, hoshi, hiru','ほ、ひ、ほす、ほし、ひる','kan','カン');
INSERT INTO all_kanji VALUES(46,'巻','ma, maku, maki','ま、まく、まき','kan','カン');
INSERT INTO all_kanji VALUES(47,'待','matsu, mataseru','まつ、またせる','tai','タイ');
INSERT INTO all_kanji VALUES(48,'看','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(49,'危','abu, aya, abunai, ayaui, ayabumu, ayauku','あぶ、あや、あぶない、あやうい、あやぶむ、あやうく','ki','キ');
INSERT INTO all_kanji VALUES(50,'揮','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(51,'貴','tatto, touto, tattoi, toutoi','たっと、とうと、たっとい、とうとい','ki','キ');
INSERT INTO all_kanji VALUES(52,'郷','n/a','','kyou, gou','キョウ、ゴウ');
INSERT INTO all_kanji VALUES(53,'警','n/a','','kei','ケイ');
INSERT INTO all_kanji VALUES(54,'穴','ana','あな','ketsu','ケツ');
INSERT INTO all_kanji VALUES(55,'絹','kinu','きぬ','ken','ケン');
INSERT INTO all_kanji VALUES(56,'憲','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(57,'源','minamoto','みなもと','gen','ゲン');
INSERT INTO all_kanji VALUES(58,'堂','n/a','','dou','ドウ');
INSERT INTO all_kanji VALUES(59,'己','onore','おのれ','ko, ki','コ、キ');
INSERT INTO all_kanji VALUES(60,'后','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(61,'孝','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(62,'紅','beni, kurenai','べに、くれない','kou, ku','コウ、ク');
INSERT INTO all_kanji VALUES(63,'鋼','hagane','はがね','kou','コウ');
INSERT INTO all_kanji VALUES(64,'刻','kiza, kizamu, kizami','きざ、きざむ、きざみ','koku','コク');
INSERT INTO all_kanji VALUES(65,'穀','n/a','','koku','コク');
INSERT INTO all_kanji VALUES(66,'砂','suna','すな','sa, sha','サ、シャ');
INSERT INTO all_kanji VALUES(67,'裁','ta, saba, tatsu, sabaku','た、さば、たつ、さばく','sai','サイ');
INSERT INTO all_kanji VALUES(68,'策','n/a','','saku','サク');
INSERT INTO all_kanji VALUES(69,'話','hana, hanasu, hanashi','はな、はなす、はなし','wa','ワ');
INSERT INTO all_kanji VALUES(70,'蚕','kaiko','かいこ','san','サン');
INSERT INTO all_kanji VALUES(71,'至','ita, itaru','いた、いたる','shi','シ');
INSERT INTO all_kanji VALUES(72,'姿','sugata','すがた','shi','シ');
INSERT INTO all_kanji VALUES(73,'視','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(74,'磁','n/a','','ji','ジ');
INSERT INTO all_kanji VALUES(75,'樹','n/a','','ju','ジュ');
INSERT INTO all_kanji VALUES(76,'宗','n/a','','shuu, sou','シュウ、ソウ');
INSERT INTO all_kanji VALUES(77,'就','tsu, tsuku','つ、つく','shuu, ju','シュウ、ジュ');
INSERT INTO all_kanji VALUES(78,'衆','n/a','','shuu, shu','シュウ、シュ');
INSERT INTO all_kanji VALUES(79,'縦','tate','たて','juu','ジュウ');
INSERT INTO all_kanji VALUES(80,'開','hira, hiraku, a, aku, akeru','ひら、ひらく、あ、あく、あける','kai','カイ');
INSERT INTO all_kanji VALUES(81,'縮','chiji, chijimu, chijimaru, chijimeru, chijireru, chijirasu','ちぢ、ちぢむ、ちぢまる、ちぢめる、ちぢれる、ちぢらす','shuku','シュク');
INSERT INTO all_kanji VALUES(82,'処','n/a','','sho','ショ');
INSERT INTO all_kanji VALUES(83,'署','n/a','','sho','ショ');
INSERT INTO all_kanji VALUES(84,'諸','n/a','','sho','ショ');
INSERT INTO all_kanji VALUES(85,'傷','kizu, ita, itamu, itameru','きず、いた、いたむ、いためる','shou','ショウ');
INSERT INTO all_kanji VALUES(86,'蒸','mu, musu, mureru, murasu','む、むす、むれる、むらす','jou','ジョウ');
INSERT INTO all_kanji VALUES(87,'針','hari','はり','shin','シン');
INSERT INTO all_kanji VALUES(88,'仁','n/a','','jin, nin','ジン、ニン');
INSERT INTO all_kanji VALUES(89,'垂','ta, tareru, tarasu, tare','た、たれる、たらす、たれ','sui','スイ');
INSERT INTO all_kanji VALUES(90,'寸','n/a','','sun','スン');
INSERT INTO all_kanji VALUES(91,'閉','to, tojiru, tozasu, shi, shimeru, shimaru','と、とじる、とざす、し、しめる、しまる','hei','ヘイ');
INSERT INTO all_kanji VALUES(92,'盛','mo, saka, moru, sakan, sakanna','も、さか、もる、さかん、さかんな','sei, jou','セイ、ジョウ');
INSERT INTO all_kanji VALUES(93,'誠','makoto','まこと','sei','セイ');
INSERT INTO all_kanji VALUES(94,'宣','n/a','','sen','セン');
INSERT INTO all_kanji VALUES(95,'泉','izumi','いずみ','sen','セン');
INSERT INTO all_kanji VALUES(96,'染','so, shi, someru, zome, somaru, shimiru, jimiru','そ、し、そめる、ぞめ、そまる、しみる、しみ','sen','セン');
INSERT INTO all_kanji VALUES(97,'善','yo, yoi','よ、よい','zen','ゼン');
INSERT INTO all_kanji VALUES(98,'奏','kana, kanaderu','かな、かなでる','sou','ソウ');
INSERT INTO all_kanji VALUES(99,'装','yosoo, yosoou','よそお、よそおう','sou, shou','ソウ、ショウ');
INSERT INTO all_kanji VALUES(100,'層','n/a','','sou','ソウ');
INSERT INTO all_kanji VALUES(101,'操','misao, ayatsu, ayatsuru','みさお、あやつ、あやつる','sou','ソウ');
INSERT INTO all_kanji VALUES(102,'友','tomo','とも','yuu','ユウ');
INSERT INTO all_kanji VALUES(103,'臓','n/a','','zou','ゾウ');
INSERT INTO all_kanji VALUES(104,'誕','n/a','','tan','タン');
INSERT INTO all_kanji VALUES(105,'暖','atata, atatakai, atatamaru, atatameru','あたた、あたたかい、あたたまる、あたためる','dan','ダン');
INSERT INTO all_kanji VALUES(106,'宙','n/a','','chuu','チュウ');
INSERT INTO all_kanji VALUES(107,'庁','n/a','','chou','チョウ');
INSERT INTO all_kanji VALUES(108,'頂','itada, itadaku, itadaki','いただ、いただく、いただき','chou','チョウ');
INSERT INTO all_kanji VALUES(109,'潮','shio','しお','chou','チョウ');
INSERT INTO all_kanji VALUES(110,'賃','n/a','','chin','チン');
INSERT INTO all_kanji VALUES(111,'討','u, utsu','う、うつ','tou','トウ');
INSERT INTO all_kanji VALUES(112,'党','n/a','','tou','トウ');
INSERT INTO all_kanji VALUES(113,'上','ue, uwa, kami, a, ageru, agaru, nobo, noboru','うえ、うわ、かみ、あ、あげる、あがる、のぼ、のぼる','jou, shou','ジョウ、ショウ');
INSERT INTO all_kanji VALUES(114,'達','tachi','たち','tatsu','タツ');
INSERT INTO all_kanji VALUES(115,'糖','n/a','','tou','トウ');
INSERT INTO all_kanji VALUES(116,'納','osa, osameru, osamaru','おさ、 おさめる、おさまる','nou, nat, na, nan, tou','ノウ、ナツ、ナ、ナン、トウ');
INSERT INTO all_kanji VALUES(117,'脳','n/a','','nou','ノウ');
INSERT INTO all_kanji VALUES(118,'拝','oga, ogamu','おが、おがむ','hai','ハイ');
INSERT INTO all_kanji VALUES(119,'肺','n/a','','hai','ハイ');
INSERT INTO all_kanji VALUES(120,'俳','n/a','','hai','ハイ');
INSERT INTO all_kanji VALUES(121,'班','n/a','','han','ハン');
INSERT INTO all_kanji VALUES(122,'秘','hi, himeru','ひ、ひめる','hi','ヒ');
INSERT INTO all_kanji VALUES(123,'腹','hara','はら','fuku','フク');
INSERT INTO all_kanji VALUES(124,'奮','furu, furuu','ふる、ふるう','fun','フン');
INSERT INTO all_kanji VALUES(125,'手','te, ta','て、た','shu, zu','シュ、ズ');
INSERT INTO all_kanji VALUES(126,'陛','n/a','','hei','ヘイ');
INSERT INTO all_kanji VALUES(127,'補','ogina, oginau','おぎな、おぎなう','ho','ホ');
INSERT INTO all_kanji VALUES(128,'宝','takara','たから','hou','ホウ');
INSERT INTO all_kanji VALUES(129,'棒','n/a','','bou','ボウ');
INSERT INTO all_kanji VALUES(130,'幕','n/a','','maku, baku','マク、バク');
INSERT INTO all_kanji VALUES(131,'密','n/a','','mitsu','ミツ');
INSERT INTO all_kanji VALUES(132,'盟','n/a','','mei','メイ');
INSERT INTO all_kanji VALUES(133,'模','n/a','','mo, bo','モ、ボ');
INSERT INTO all_kanji VALUES(134,'郵','n/a','','yuu','ユウ');
INSERT INTO all_kanji VALUES(135,'幼','osanai','おさない','you','ヨウ');
INSERT INTO all_kanji VALUES(136,'紙','kami','かみ','shi','シ');
INSERT INTO all_kanji VALUES(137,'翌','n/a','','yoku','ヨク');
INSERT INTO all_kanji VALUES(138,'卵','tamago','たまご','ran','ラン');
INSERT INTO all_kanji VALUES(139,'覧','n/a','','ran','ラン');
INSERT INTO all_kanji VALUES(140,'裏','ura','うら','ri','リ');
INSERT INTO all_kanji VALUES(141,'臨','nozo, nozomu','のぞ、のぞむ','rin','リン');
INSERT INTO all_kanji VALUES(142,'朗','hoga, hogarakana','ほが、ほがらかな','rou','ロウ');
INSERT INTO all_kanji VALUES(143,'依','n/a','','i, e','イ、エ');
INSERT INTO all_kanji VALUES(144,'違','chiga, chigau, chigaeru','ちが、ちがう、ちがえる','i','イ');
INSERT INTO all_kanji VALUES(145,'鋭','surudo, surudoi','するど、するどい','ei','エイ');
INSERT INTO all_kanji VALUES(146,'煙','kemu, kemuru, kemui, kemuri','けむ、けむる、けむい、けむり','en','エン');
INSERT INTO all_kanji VALUES(147,'書','ka, kaku','か、かく','sho','ショ');
INSERT INTO all_kanji VALUES(148,'汚','kega, yogo, kitana, kegasu, kegareru, kegarawashii, yogosu, yogoreru, kitanai','けが、よご、きたな、けがす、けがれる、けがらわしい、よごす、よごれる、きたない','o','オ');
INSERT INTO all_kanji VALUES(149,'押','o, osu, osaeru','お、おす、おさえる','ou','オウ');
INSERT INTO all_kanji VALUES(150,'欧','n/a','','ou','オウ');
INSERT INTO all_kanji VALUES(151,'菓','n/a','','ka','カ');
INSERT INTO all_kanji VALUES(152,'靴','kutsu','くつ','ka','カ');
INSERT INTO all_kanji VALUES(153,'掛','ka, kakeru, kake, kakaru, kakari','か、かける、かけ、かかる、かかり','n/a','');
INSERT INTO all_kanji VALUES(154,'汗','ase','あせ','kan','カン');
INSERT INTO all_kanji VALUES(155,'缶','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(156,'患','wazura, wazurau','わずら、わずらう','kan','カン');
INSERT INTO all_kanji VALUES(157,'幾','iku, ikutsu, ikura','いく、いくつ、いくら','ki','キ');
INSERT INTO all_kanji VALUES(158,'秋','aki','あき','shuu','シュウ');
INSERT INTO all_kanji VALUES(159,'詰','tsu, tsumeru, tsumaru, tsumu','つ、つめる、つまる、つむ','kitsu','キツ');
INSERT INTO all_kanji VALUES(160,'叫','sake, sakebu','さけ、さけぶ','kyou','キョウ');
INSERT INTO all_kanji VALUES(161,'況','n/a','','kyou','キョウ');
INSERT INTO all_kanji VALUES(162,'挟','hasa, hasamu, hasamaru','はさ、はさむ、はさまる','kyou','キョウ');
INSERT INTO all_kanji VALUES(163,'偶','n/a','','guu','グウ');
INSERT INTO all_kanji VALUES(164,'隅','sumi','すみ','guu','グウ');
INSERT INTO all_kanji VALUES(165,'掘','ho, horu','ほ、ほる','kutsu','クツ');
INSERT INTO all_kanji VALUES(166,'傾','katamu, kashi, katamukeru, katamuku, kashigeru','かたむ、かし、かたむける、かたむく、かしげる','kei','ケイ');
INSERT INTO all_kanji VALUES(167,'軒','noki','のき','ken','ケン');
INSERT INTO all_kanji VALUES(168,'枯','ka, kareru, karasu','か、かれる、からす','ko','コ');
INSERT INTO all_kanji VALUES(169,'山','yama','やま','san','サン');
INSERT INTO all_kanji VALUES(170,'雇','yato, yatou','やと、やとう','ko','コ');
INSERT INTO all_kanji VALUES(171,'更','sara, fu, sarani, fukeru, fukasu','さら、ふ、さらに、ふける、ふかす','kou','コウ');
INSERT INTO all_kanji VALUES(172,'肯','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(173,'荒','ara, a, arai, arasu, areru','あら、あ、あらい、あらす、あれる','kou','コウ');
INSERT INTO all_kanji VALUES(174,'郊','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(175,'香','ka, kao, kaori, kaoru','か、かお、かおり、かおる','kou, kyou','コウ、キョウ');
INSERT INTO all_kanji VALUES(176,'硬','kata, katai','かた、かたい','kou','コウ');
INSERT INTO all_kanji VALUES(177,'込','ko, komu, komeru','こ、こむ、こめる','n/a','');
INSERT INTO all_kanji VALUES(178,'歳','n/a','','sai, sei','サイ、セイ');
INSERT INTO all_kanji VALUES(179,'咲','sa, saku','さ、さく','n/a','');
INSERT INTO all_kanji VALUES(180,'雪','yuki','ゆき','setsu','セツ');
INSERT INTO all_kanji VALUES(181,'脂','abura','あぶら','shi','シ');
INSERT INTO all_kanji VALUES(182,'湿','shime, shimeru, shimesu','しめ、しめる、しめす','shitsu','シツ');
INSERT INTO all_kanji VALUES(183,'舟','fune, funa','ふね、ふな','shuu','シュウ');
INSERT INTO all_kanji VALUES(184,'柔','yawa, yawarakai, yawana','やわ、やわらかい、やわな','juu, nyuu','ジュウ、ニュウ');
INSERT INTO all_kanji VALUES(185,'緒','o','お','sho, cho','ショ、チョ');
INSERT INTO all_kanji VALUES(186,'召','me, mesu','め、めす','shou','ショウ');
INSERT INTO all_kanji VALUES(187,'床','toko, yuka','とこ、ゆか','shou','ショウ');
INSERT INTO all_kanji VALUES(188,'昇','nobo, noboru','のぼ、のぼる','shou','ショウ');
INSERT INTO all_kanji VALUES(189,'畳','tata, tatamu, tatami','たた、たたむ、たたみ','jou','ジョウ');
INSERT INTO all_kanji VALUES(190,'触','fu, sawa, fureru, sawaru','ふ、さわ、ふれる、さわる','shoku','ショク');
INSERT INTO all_kanji VALUES(191,'雨','ame, ama','あめ、あま','u','ウ');
INSERT INTO all_kanji VALUES(192,'伸','no, nobiru, nobasu','の、のびる、のばす','shin','シン');
INSERT INTO all_kanji VALUES(193,'吹','fu, fuku','ふ、ふく','sui','スイ');
INSERT INTO all_kanji VALUES(194,'姓','n/a','','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(195,'隻','n/a','','seki','セキ');
INSERT INTO all_kanji VALUES(196,'跡','ato','あと','seki','セキ');
INSERT INTO all_kanji VALUES(197,'籍','n/a','','seki','セキ');
INSERT INTO all_kanji VALUES(198,'占','shi, urana, shimeru, uranau','し、うらな、しめる、うらなう','sen','セン');
INSERT INTO all_kanji VALUES(199,'双','futa','ふた','sou','ソウ');
INSERT INTO all_kanji VALUES(200,'捜','saga, sagasu','さが、さがす','sou','ソウ');
INSERT INTO all_kanji VALUES(201,'掃','ha, haku','は、はく','sou','ソウ');
INSERT INTO all_kanji VALUES(202,'当','a, atari, ataru, ateru','あ、あたり、あたる、あてる','tou','トウ');
INSERT INTO all_kanji VALUES(203,'燥','n/a','','sou','ソウ');
INSERT INTO all_kanji VALUES(204,'憎','niku, nikumu, nikui, nikurashii, nikushimi','にく、にくむ、にくい、にくらしい、にくしみ','zou','ゾウ');
INSERT INTO all_kanji VALUES(205,'贈','oku, okuru','おく、おくる','zou, sou','ゾウ、ソウ');
INSERT INTO all_kanji VALUES(206,'袋','fukuro','ふくろ','tai','タイ');
INSERT INTO all_kanji VALUES(207,'替','ka, kawaru, kaeru','か、かわる、かえる','tai','タイ');
INSERT INTO all_kanji VALUES(208,'濯','n/a','','taku','タク');
INSERT INTO all_kanji VALUES(209,'畜','n/a','','chiku','チク');
INSERT INTO all_kanji VALUES(210,'駐','n/a','','chuu','チュウ');
INSERT INTO all_kanji VALUES(211,'超','ko, koeru, kosu','こ、こえる、こす','chou','チョウ');
INSERT INTO all_kanji VALUES(212,'沈','shizu, shizumu, shizumeru','しず、しずむ、しずめる','chin','チン');
INSERT INTO all_kanji VALUES(213,'飲','no, nomu','の、のむ','in','イン');
INSERT INTO all_kanji VALUES(214,'珍','mezura, mezurashii','めずら、めずらしい','chin','チン');
INSERT INTO all_kanji VALUES(215,'泥','doro','どろ','dei','デイ');
INSERT INTO all_kanji VALUES(216,'滴','shizuku, shitata, shitataru','しずく、したた、したたる','teki','テキ');
INSERT INTO all_kanji VALUES(217,'殿','tono','との','den, ten','デン、テン');
INSERT INTO all_kanji VALUES(218,'塗','nu, nuru, nuri','ぬ、ぬる、ぬり','to','ト');
INSERT INTO all_kanji VALUES(219,'逃','ni, noga, nigeru, nigasu, nogasu, nogareru','に、のが、にげる、にがす、のがす、のがれる','tou','トウ');
INSERT INTO all_kanji VALUES(220,'塔','n/a','','tou','トウ');
INSERT INTO all_kanji VALUES(221,'筒','tsutsu','つつ','tou','トウ');
INSERT INTO all_kanji VALUES(222,'鈍','nibu, nibui, niburu','にぶ、にぶい、にぶる','don','ドン');
INSERT INTO all_kanji VALUES(223,'軟','yawa, yawarakai','やわ、やわらかい','nan','ナン');
INSERT INTO all_kanji VALUES(224,'下','shita, shimo, sa, sagaru, sageru, kuda, kudaru, kudasai, o, orosu, oriru','した、しも、さ、さがる、さげる、くだ、くだる、ください、お、おろす、おりる','ka, ge','カ、ゲ');
INSERT INTO all_kanji VALUES(225,'知','shi, shiru, shirasu, shiraseru','し、しる、しらす、しらせる','chi','チ');
INSERT INTO all_kanji VALUES(226,'悩','naya, nayamu, nayami, nayamasu','なや、なやむ、なやみ、なやます','nou','ノウ');
INSERT INTO all_kanji VALUES(227,'濃','ko, koi, kosa','こ、こい、こさ','nou','ノウ');
INSERT INTO all_kanji VALUES(228,'泊','tomaru, tomeru','とまる、とめる','haku','ハク');
INSERT INTO all_kanji VALUES(229,'薄','usu, usui, usumeru, usumaru, usuragu, usureru','うす、うすい、うすめる、うすまる、うすらぐ、うすれる','haku','ハス');
INSERT INTO all_kanji VALUES(230,'爆','n/a','','baku','バク');
INSERT INTO all_kanji VALUES(231,'肌','hada','はだ','n/a','');
INSERT INTO all_kanji VALUES(232,'髪','kami','かみ','hatsu','ハツ');
INSERT INTO all_kanji VALUES(233,'販','n/a','','han','ハン');
INSERT INTO all_kanji VALUES(234,'瓶','n/a','','bin','ビン');
INSERT INTO all_kanji VALUES(235,'浮','u, uku, ukareru, ukabu, ukaberu','う、うく、うかれる、うかぶ、うかべる','fu','フ');
INSERT INTO all_kanji VALUES(236,'前','mae','まえ','zen','ゼン');
INSERT INTO all_kanji VALUES(237,'膚','n/a','','fu','フ');
INSERT INTO all_kanji VALUES(238,'舞','ma, mau, mai','ま、まう、まい','bu','ブ');
INSERT INTO all_kanji VALUES(239,'封','n/a','','fuu, hou','フウ、ホウ');
INSERT INTO all_kanji VALUES(240,'幅','haba','はば','fuku','フク');
INSERT INTO all_kanji VALUES(241,'沸','wa, waku, wakasu','わ、わく、わかす','futsu','フツ');
INSERT INTO all_kanji VALUES(242,'捕','to, tsuka, toraeru, torawareru, toru, tsukamaeru, tsukamaru','と、つか、とらえる、とらわれる、とる、つかまえる、つかまる','ho','ホ');
INSERT INTO all_kanji VALUES(243,'抱','da, ida, kaka, daku, idaku, kakaeru','だ、いだ、かか、だく、いだく、かかえる','hou','ホウ');
INSERT INTO all_kanji VALUES(244,'帽','n/a','','bou','ボウ');
INSERT INTO all_kanji VALUES(245,'磨','miga, migaku','みが、みがく','ma','マ');
INSERT INTO all_kanji VALUES(246,'埋','u, umeru, umaru, umoreru','う、うめる、うまる、うもれる','mai','マイ');
INSERT INTO all_kanji VALUES(247,'後','nochi, ushi, ushiro, ato, oku, okure','のち、うし、うしろ、あと、おく、おくれ','go, kou','ゴ、コウ');
INSERT INTO all_kanji VALUES(248,'溶','to, tokeru, tokasu, toku','と、とける、とかす、とく','you','ヨウ');
INSERT INTO all_kanji VALUES(249,'腰','koshi','こし','you','ヨウ');
INSERT INTO all_kanji VALUES(250,'踊','odo, odoru, odori','おど、おどる、おどり','you','ヨウ');
INSERT INTO all_kanji VALUES(251,'粒','tsubu','つぶ','ryuu','リュウ');
INSERT INTO all_kanji VALUES(252,'了','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(253,'涼','suzu, suzushii, suzumu','すず、すずしい、すずむ','ryou','リョウ');
INSERT INTO all_kanji VALUES(254,'療','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(255,'涙','namida','なみだ','rui','ルイ');
INSERT INTO all_kanji VALUES(256,'零','n/a','','rei','レイ');
INSERT INTO all_kanji VALUES(257,'齢','n/a','','rei','レイ');
INSERT INTO all_kanji VALUES(258,'授','sazu, sazukeru, sazukaru','さず、 さずける、さずかる','ju','ジュ');
INSERT INTO all_kanji VALUES(259,'湾','n/a','','wan','ワン');
INSERT INTO all_kanji VALUES(260,'腕','ude','うで','wan','ワン');
INSERT INTO all_kanji VALUES(261,'離','hanareru, hanasu, hana','はなれる、はなす、はな','ri','リ');
INSERT INTO all_kanji VALUES(262,'々','n/a','n/a','n/a','');
INSERT INTO all_kanji VALUES(263,'脱','nu, nugu, nugeru','ぬ、ぬぐ、ぬげる','datsu','ダツ');
INSERT INTO all_kanji VALUES(264,'較','n/a','','kaku','カク');
INSERT INTO all_kanji VALUES(265,'業','waza','わざ','gyou, gou','ギョウ、ゴウ');
INSERT INTO all_kanji VALUES(266,'遅','oku, oso, okureru, okurasu, osoi, osoku','おく、おそ、おくれる、おくらす、おそい、おそく','chi','チ');
INSERT INTO all_kanji VALUES(267,'思','omo, omou, omoi','おも、おもう、おもい','shi','シ');
INSERT INTO all_kanji VALUES(268,'夜','yo, yoru','よ、よる','ya','ヤ');
INSERT INTO all_kanji VALUES(269,'映','utsu, ha, utsuru, utsusu, haeru','うつ、は、うつる、うつす、はえる','ei','エイ');
INSERT INTO all_kanji VALUES(270,'画','n/a','','ga, kaku','ガ、カク');
INSERT INTO all_kanji VALUES(271,'中','naka','なか','chuu','チュウ');
INSERT INTO all_kanji VALUES(272,'出','de, da, deru, dasu','で、だ、でる、だす','shutsu, sui','シュツ、スイ');
INSERT INTO all_kanji VALUES(273,'電','n/a','','den','デン');
INSERT INTO all_kanji VALUES(274,'会','a, au','あ、あう','kai, e','カイ、エ');
INSERT INTO all_kanji VALUES(275,'物','mono','もの','butsu, motsu','ブツ、モツ');
INSERT INTO all_kanji VALUES(276,'返','kae, kaesu, kaeru, kaeri','かえ、かえす、かえる、かえり','hen','ヘン');
INSERT INTO all_kanji VALUES(277,'簡','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(278,'単','n/a','','tan','タン');
INSERT INTO all_kanji VALUES(279,'直','tada, tadasu, nao, naoru, naosu','ただ、ただす、なお、なおる、なおす','choku, jiki, jika','チョク、ジキ、ジカ');
INSERT INTO all_kanji VALUES(280,'習','nara, narau, narai','なら、ならう、ならい','shuu','シュウ');
INSERT INTO all_kanji VALUES(281,'困','koma, komaru','こま、こまる','kon','コン');
INSERT INTO all_kanji VALUES(282,'右','migi','みぎ','u, yuu','ウ、ユウ');
INSERT INTO all_kanji VALUES(283,'持','mo, motsu, mochi','も、もつ、もち','ji','ジ');
INSERT INTO all_kanji VALUES(284,'調','shira, totono, shiraberu, totonoeru, totonou','しら、ととの、しらべる、ととのえる、ととのう','chou','チョウ');
INSERT INTO all_kanji VALUES(285,'引','hi, hiku','ひ、ひく','in','イン');
INSERT INTO all_kanji VALUES(286,'聞','ki, kiku, kikoeru','き、きく、きこえる','bun, mon','ブン、モン');
INSERT INTO all_kanji VALUES(287,'野','no','の','ya','ヤ');
INSERT INTO all_kanji VALUES(288,'村','mura','むら','son','ソン');
INSERT INTO all_kanji VALUES(289,'背','se, sei, somuku, somukeru','せ、せい、そむく、そむける','hai','ハイ');
INSERT INTO all_kanji VALUES(290,'高','taka, takai, takasa, takamaru, takaburu, takameru','たか、たかい、たかさ、たかまる、たかぶる、たかめる','kou','コウ');
INSERT INTO all_kanji VALUES(291,'低','hiku, hikui, hikumaru, hikumeru','ひく、ひくい、ひくまる、ひくめる','tei','テイ');
INSERT INTO all_kanji VALUES(292,'長','naga, nagai','なが、ながい','chou','チョウ');
INSERT INTO all_kanji VALUES(293,'左','hidari','ひだり','sa','サ');
INSERT INTO all_kanji VALUES(294,'短','mijika, mijikai','みじか、みじかい','tan','タン');
INSERT INTO all_kanji VALUES(295,'着','ki, tsu, kiru, kiseru, tsuku','き、つ、きる、きせる、つく','chaku, jaku','チャク、ジャク');
INSERT INTO all_kanji VALUES(296,'楽','tano, tanoshimu, tanoshii, tanoshimi','たの、たのしむ、たのしい、たのしみ','gaku, raku','ガク、ラク');
INSERT INTO all_kanji VALUES(297,'川','kawa','かわ','sen','セン');
INSERT INTO all_kanji VALUES(298,'質','n/a','','shitsu, shichi, chi','シツ、シチ、チ');
INSERT INTO all_kanji VALUES(299,'問','to, tou, toi, ton','と、とう、とい、とん','mon','モン');
INSERT INTO all_kanji VALUES(300,'以','mo, motte','も、もって','i','イ');
INSERT INTO all_kanji VALUES(301,'多','oo, ooi, ooku','おお、おおい、おおく','ta','タ');
INSERT INTO all_kanji VALUES(302,'若','wakai, waka, mo, moshi','わかい、わか、も、もし','jaku, nyaku','ジャク、ニャク');
INSERT INTO all_kanji VALUES(303,'太','futo, futoru, futoi, futotta, futosa','ふと、ふとる、ふとい、ふとった、ふとさ','tai, ta','タイ、タ');
INSERT INTO all_kanji VALUES(304,'色','iro','いろ','shoku, shiki','ショク、シキ');
INSERT INTO all_kanji VALUES(305,'止','to, ya, tomeru, tomaru, yamu, yameru','と、や、とめる、とまる、やむ、やめる','shi','シ');
INSERT INTO all_kanji VALUES(306,'遠','too, tooi, tooku','とお、とおい、とおく','en, on','エン、オン');
INSERT INTO all_kanji VALUES(307,'忙','isoga, isogashii','いそが、いそがしい','bou','ボウ');
INSERT INTO all_kanji VALUES(308,'借','ka, kariru','か、かりる','shaku','シャク');
INSERT INTO all_kanji VALUES(309,'茶','n/a','','cha, sa','チャ、サ');
INSERT INTO all_kanji VALUES(310,'入','i, hai, iri, iru, hairu, ireru, ire','い、はい、いり、いる、はいる、いれる、いれ','nyuu','ニュウ');
INSERT INTO all_kanji VALUES(311,'新','ara, atara, atarashii, arata, nii','あら、あたら、あたらしい、あらた、にい','shin','シン');
INSERT INTO all_kanji VALUES(312,'教','oshi, oso, oshieru, osowaru','おし、おそ、おしえる、おそわる','kyou','キョウ');
INSERT INTO all_kanji VALUES(313,'味','aji, ajiwau, ajiwai','あじ、あじわう、あじわい','mi','ミ');
INSERT INTO all_kanji VALUES(314,'白','shiro, shira, shiroi','しろ、しら、しろい','haku, byaku','ハク、ビャク');
INSERT INTO all_kanji VALUES(315,'女','onna, me','おんな、め','jo, nyo, nyou','ジョ、ニョ、ニョウ');
INSERT INTO all_kanji VALUES(316,'青','ao, aoi','あお、あおい','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(317,'黒','kuroi, kuro','くろい、くろ','koku','コク');
INSERT INTO all_kanji VALUES(318,'方','kata','かた','hou','ホウ');
INSERT INTO all_kanji VALUES(319,'運','hako, hakobu','はこ、はこぶ','un','ウン');
INSERT INTO all_kanji VALUES(320,'動','ugo, ugoku, ugokasu, ugoki','うご、うごく、うごかす、うごき','dou','ドウ');
INSERT INTO all_kanji VALUES(321,'体','karada','からだ','tai, tei','タイ、テイ');
INSERT INTO all_kanji VALUES(322,'痛','ita, itai, itamu, itamashii, itameru, itami','いた、いたい、いたむ、いたましい、いためる、いたみ','tsuu','ツウ');
INSERT INTO all_kanji VALUES(323,'元','moto','もと','gen, gan','ゲン、ガン');
INSERT INTO all_kanji VALUES(324,'気','n/a','','ki, ke','キ、ケ');
INSERT INTO all_kanji VALUES(325,'変','ka, kawaru, kawari, kaeru','か、かわる、かわり、かえる','hen','ヘン');
INSERT INTO all_kanji VALUES(326,'男','otoko','おとこ','dan, nan','ダン、ナン');
INSERT INTO all_kanji VALUES(327,'疲','tsuka, tsukareru, tsukare','つか、つかれる、つかれ','hi','ヒ');
INSERT INTO all_kanji VALUES(328,'寝','ne, neru, nekasu, nekaseru','ね、ねる、ねかす、ねかせる','shin','シン');
INSERT INTO all_kanji VALUES(329,'天','ame, ama','あめ、あま','ten','テン');
INSERT INTO all_kanji VALUES(330,'頭','atama, kashira','あたま、かしら','tou, zu, to','トウ、ズ、ト');
INSERT INTO all_kanji VALUES(331,'図','haka, hakaru','はか、はかる','zu, to','ズ、ト');
INSERT INTO all_kanji VALUES(332,'館','tate','たて','kan','カン');
INSERT INTO all_kanji VALUES(333,'探','sagu, saga, saguru, sagasu','さぐ、さが、さぐる、さがす','tan','タン');
INSERT INTO all_kanji VALUES(334,'失','ushina, ushinau','うしな、うしなう','shitsu','シツ');
INSERT INTO all_kanji VALUES(335,'礼','n/a','','rei, rai','レイ、ライ');
INSERT INTO all_kanji VALUES(336,'少','suku, suko, sukunai, sukoshi','すく、すこ、すくない、すこし','shou','ショウ');
INSERT INTO all_kanji VALUES(337,'人','hito','ひと','jin, nin','ジン、ニン');
INSERT INTO all_kanji VALUES(338,'自','mizuka, ono, mizukara, onozukara','みずか、おの、みずから、おのずから','ji, shi','ジ、シ');
INSERT INTO all_kanji VALUES(339,'由','yoshi','よし','yu, yuu, yui','ユ、ユウ、ユイ');
INSERT INTO all_kanji VALUES(340,'無','na, nai, nashi, nakusu, nakunaru','な、ない、なし、なくす、なくなる','mu, bu','ム、ブ');
INSERT INTO all_kanji VALUES(341,'理','n/a','','ri','リ');
INSERT INTO all_kanji VALUES(342,'言','i, iu, koto','い、いう、こと','gen, gon','ゲン、ゴン');
INSERT INTO all_kanji VALUES(343,'度','tabi','たび','do, to, taku','ド、ト、タク');
INSERT INTO all_kanji VALUES(344,'集','atsu, tsudo, atsumaru, atsumari, atsumeru, tsudou, tsudoi','あつ、つど、あつまる、あつまり、あつめる、つどう、つどい','shuu','シュウ');
INSERT INTO all_kanji VALUES(345,'音','oto, ne','おと、ね','on, non, in','オン、ノン、イン');
INSERT INTO all_kanji VALUES(346,'決','ki, kimeru, kimaru','き、きめる、きまる','ketsu','ケツ');
INSERT INTO all_kanji VALUES(347,'事','koto','こと','ji, zu','ジ、ズ');
INSERT INTO all_kanji VALUES(348,'二','futa, futatsu, futari','ふた、ふたつ、ふたり','ni','ニ');
INSERT INTO all_kanji VALUES(349,'見','mi, miru, mieru, miseru','み、みる、みえる、みせる','ken','ケン');
INSERT INTO all_kanji VALUES(350,'切','ki, kiru, kiri, kireru','き、きる、きり、きれる','setsu, sai','セツ、サイ');
INSERT INTO all_kanji VALUES(351,'符','n/a','','fu','フ');
INSERT INTO all_kanji VALUES(352,'悪','waru, a, warui, warusa, ashi, ashiki','わる、あ、わるい、わるさ、あし、あしき','aku, o','アク、オ');
INSERT INTO all_kanji VALUES(353,'実','mi, mino, minoru, minori','み、みの、みのる、みのり','jitsu','ジツ');
INSERT INTO all_kanji VALUES(354,'病','ya, yamu, yami, yamai','や、やむ、やみ、やまい','byou, hei','ビョウ、ヘイ');
INSERT INTO all_kanji VALUES(355,'治','osa, nao, osameru, osamaru, naoru, naosu','おさ、なお、おさめる、おさまる、なおる、なおす','ji, chi','ジ、チ');
INSERT INTO all_kanji VALUES(356,'校','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(357,'心','kokoro','こころ','shin','シン');
INSERT INTO all_kanji VALUES(358,'発','ta, tatsu','た、たつ','hatsu, hotsu','ハツ、ホツ');
INSERT INTO all_kanji VALUES(359,'番','n/a','','ban','バン');
INSERT INTO all_kanji VALUES(360,'先','saki','さき','sen','セン');
INSERT INTO all_kanji VALUES(361,'英','n/a','','ei','エイ');
INSERT INTO all_kanji VALUES(362,'文','fumi','ふみ','bun, mon','ブン、モン');
INSERT INTO all_kanji VALUES(363,'法','n/a','','hou, hatsu, hotsu','ホウ、ハツ、ホツ');
INSERT INTO all_kanji VALUES(364,'練','ne, neru, neri','ね、ねる、ねり','ren','レン');
INSERT INTO all_kanji VALUES(365,'貸','ka, kasu, kashi','か、かす、かし','tai','タイ');
INSERT INTO all_kanji VALUES(366,'森','mori','もり','shin','シン');
INSERT INTO all_kanji VALUES(367,'試','kokoro, tame, kokoromiru, kokoromi, tamesu, tameshi','こころ、ため、こころみる、こころみ、ためす、ためし','shi','シ');
INSERT INTO all_kanji VALUES(368,'験','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(369,'題','n/a','','dai','ダイ');
INSERT INTO all_kanji VALUES(370,'全','matta, mattaku, sube, subete','まった、まったく、すべ、すべて','zen','ゼン');
INSERT INTO all_kanji VALUES(371,'車','kuruma','くるま','sha','シャ');
INSERT INTO all_kanji VALUES(372,'部','n/a','','bu','ブ');
INSERT INTO all_kanji VALUES(373,'目','me, ma','め、ま','moku','モク');
INSERT INTO all_kanji VALUES(374,'号','n/a','','gou','ゴウ');
INSERT INTO all_kanji VALUES(375,'研','to, togu','と、とぐ','ken','ケン');
INSERT INTO all_kanji VALUES(376,'究','kiwa, kiwameru','きわ、きわめる','kyuu','キュウ');
INSERT INTO all_kanji VALUES(377,'室','muro','むろ','shitsu','シツ');
INSERT INTO all_kanji VALUES(378,'連','tsura, tsu, tsuranaru, tsuraneru, tsureru, tsure','つら、つ、つらなる、つらねる、つれる、つれ','ren','レン');
INSERT INTO all_kanji VALUES(379,'花','hana','はな','ka','カ');
INSERT INTO all_kanji VALUES(380,'仕','tsuka, tsukaeru','つか、つかえる','shi, ji','シ、ジ');
INSERT INTO all_kanji VALUES(381,'経','he, ta, heru, tatsu','へ、た、へる、たつ','kei, kyou','ケイ、キョウ');
INSERT INTO all_kanji VALUES(382,'国','kuni','くに','koku','コク');
INSERT INTO all_kanji VALUES(383,'済','su, sumu, sumi, sumasu, sumaseru','す、すむ、すみ、すます、すませる','sai','サイ');
INSERT INTO all_kanji VALUES(384,'的','mato','まと','teki','テキ');
INSERT INTO all_kanji VALUES(385,'難','kata, muzuka, katai, katasa, muzukashii','かた、むずか、かたい、かたさ、むずかしい','nan','ナン');
INSERT INTO all_kanji VALUES(386,'広','hiro, hiromaru, hiromeru, hirogaru, hirogeru, hiroi, hirosa','ひろ、ひろまる、ひろめる、ひろがる、ひろげる、ひろい、ひろさ','kou','コウ');
INSERT INTO all_kanji VALUES(387,'同','ona, onaji, onajiku','おな、おなじ、おなじく','dou','ドウ');
INSERT INTO all_kanji VALUES(388,'夏','natsu','なつ','ka, ge','カ、ゲ');
INSERT INTO all_kanji VALUES(389,'春','haru','はる','shun','シュン');
INSERT INTO all_kanji VALUES(390,'必','kanara, kanarazu','かなら、かならず','hitsu','ヒツ');
INSERT INTO all_kanji VALUES(391,'要','i, kaname, iru','い、かなめ、いる','you','ヨウ');
INSERT INTO all_kanji VALUES(392,'交','maji, ma, ka, majiwaru, majieru, majiru, mazaru, mazeru, kau, kawasu','まじ、ま、か、まじわる、まじえる、まじる、まざる、まぜる、かう、かわす','kou','コウ');
INSERT INTO all_kanji VALUES(393,'時','toki','とき','ji','ジ');
INSERT INTO all_kanji VALUES(394,'通','too, kayo, tooru, toori, toosu, tooshi, kayou','とお、かよ、とおる、とおり、とおす、とおし、かよう','tsuu, tsu','ツウ、ツ');
INSERT INTO all_kanji VALUES(395,'冬','fuyu','ふゆ','tou','トウ');
INSERT INTO all_kanji VALUES(396,'走','hashi, hashiru, hashiri','はし、はしる、はしり','sou','ソウ');
INSERT INTO all_kanji VALUES(397,'重','e, omo, kasa, omoi, omosa, omori, omotai, omoshi, kasaneru, kasanaru','え、おも、かさ、おもい、おもさ、おもり、おもたい、おもし、かさねる、かさなる','juu, chou','ジュウ、チョウ');
INSERT INTO all_kanji VALUES(398,'卒','n/a','','sotsu','ソツ');
INSERT INTO all_kanji VALUES(399,'社','yashiro','やしろ','sha','シャ');
INSERT INTO all_kanji VALUES(400,'勤','tsuto, tsutomeru, tsutomaru','つと、つとめる、つとまる','kin, gon','キン、ゴン');
INSERT INTO all_kanji VALUES(401,'屋','ya','や','oku','オク');
INSERT INTO all_kanji VALUES(402,'午','n/a','','go','ゴ');
INSERT INTO all_kanji VALUES(403,'机','tsukue','つくえ','ki','キ');
INSERT INTO all_kanji VALUES(404,'間','aida, ma','あいだ、ま','kan, ken','カン、ケン');
INSERT INTO all_kanji VALUES(405,'使','tsuka, tsukau, tsukai','つか、つかう、つかい','shi','シ');
INSERT INTO all_kanji VALUES(406,'寒','samu, samui','さむ、さむい','kan','カン');
INSERT INTO all_kanji VALUES(407,'暑','atsu, atsui, atsusa','あつ、あつい、あつさ','sho','ショ');
INSERT INTO all_kanji VALUES(408,'冷','tsume, hi, sa, tsumetai, hieru, hiya, hiyayaka, hiyasu, hiyakasu, sameru, samasu','つめ、ひ、さ、つめたい、ひえる、ひや、ひややか、ひやす、ひやかす、さめる、さます','rei','レイ');
INSERT INTO all_kanji VALUES(409,'誰','dare','だれ','sui','スイ');
INSERT INTO all_kanji VALUES(410,'急','iso, isogu, isogi','いそ、いそぐ、いそぎ','kyuu','キュウ');
INSERT INTO all_kanji VALUES(411,'用','mochi, mochiiru','もち、もちいる','you','ヨウ');
INSERT INTO all_kanji VALUES(412,'頃','koro','ころ','kei','ケイ');
INSERT INTO all_kanji VALUES(413,'内','uchi','うち','nai','ナイ');
INSERT INTO all_kanji VALUES(414,'伝','tsuta, tsutawaru, tsutaeru, tsutau, tsutai','つた、つたわる、つたえる、つたう、つたい','den','デン');
INSERT INTO all_kanji VALUES(415,'半','naka, nakaba','なか、なかば','han','ハン');
INSERT INTO all_kanji VALUES(416,'欲','ho, hossuru, hoshii','ほ、ほっする、ほしい','yoku','ヨク');
INSERT INTO all_kanji VALUES(417,'初','haji, hatsu, ui, so, hajimete, hajime, hatsu, someru','はじ、はつ、うい、そ、はじめて、はじめ、はつ、そめる','sho','ショ');
INSERT INTO all_kanji VALUES(418,'次','tsu, tsugu, tsugi','つ、つぐ、つぎ','ji, shi','ジ、シ');
INSERT INTO all_kanji VALUES(419,'最','motto, mottomo','もっと、もっとも','sai','サイ');
INSERT INTO all_kanji VALUES(420,'田','ta','た','den','デン');
INSERT INTO all_kanji VALUES(421,'石','ishi','いし','seki, shaku, koku','セキ、シャク、コク');
INSERT INTO all_kanji VALUES(422,'原','hara','はら','gen','ゲン');
INSERT INTO all_kanji VALUES(423,'駅','n/a','','eki','エキ');
INSERT INTO all_kanji VALUES(424,'辺','ata, atari, be','あた、あたり、べ','hen','ヘン');
INSERT INTO all_kanji VALUES(425,'道','michi','みち','dou, tou','ドウ、トウ');
INSERT INTO all_kanji VALUES(426,'分','wa, wakeru, wakaru, wakareru','わ、わける、わかる、わかれる','bun, fun, bu','ブン、フン、ブ');
INSERT INTO all_kanji VALUES(427,'然','n/a','','zen, nen','ゼン、ネン');
INSERT INTO all_kanji VALUES(428,'工','n/a','','kou, ku','コウ、ク');
INSERT INTO all_kanji VALUES(429,'所','tokoro','ところ','sho','ショ');
INSERT INTO all_kanji VALUES(430,'横','yoko','よこ','ou','オウ');
INSERT INTO all_kanji VALUES(431,'信','n/a','','shin','シン');
INSERT INTO all_kanji VALUES(432,'曲','ma, magaru, mageru','ま、まがる、まげる','kyoku','キョク');
INSERT INTO all_kanji VALUES(433,'橋','hashi','はし','kyou','キョウ');
INSERT INTO all_kanji VALUES(434,'向','mu, muku, muki, mukeru, mukau, mukou','む、むく、むき、むける、むかう、むこう','kou','コウ');
INSERT INTO all_kanji VALUES(435,'地','n/a','','chi, ji','チ、ジ');
INSERT INTO all_kanji VALUES(436,'銀','n/a','','gin','ギン');
INSERT INTO all_kanji VALUES(437,'月','tsuki','つき','getsu, gatsu','ゲツ、ガツ');
INSERT INTO all_kanji VALUES(438,'角','kado, tsuno','かど、つの','kaku','カク');
INSERT INTO all_kanji VALUES(439,'赤','aka, akai, akaramu, akarameru','あか、あかい、あからむ、あからめる','seki, shaku','セキ、シャク');
INSERT INTO all_kanji VALUES(440,'祝','iwa, iwau, iwai','いわ、いわう、いわい','shuku, shuu','シュク、シュウ');
INSERT INTO all_kanji VALUES(441,'相','ai','あい','sou, shou','ソウ、ショウ');
INSERT INTO all_kanji VALUES(442,'談','n/a','','dan','ダン');
INSERT INTO all_kanji VALUES(443,'接','tsu, tsugu','つ、つぐ','setsu','セツ');
INSERT INTO all_kanji VALUES(444,'料','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(445,'払','hara, harau, harai','はら、はらう、はらい','futsu','フツ');
INSERT INTO all_kanji VALUES(446,'期','n/a','','ki, go','キ、ゴ');
INSERT INTO all_kanji VALUES(447,'働','hatara, hataraku, hataraki','はたら、はたらく、はたらき','dou','ドウ');
INSERT INTO all_kanji VALUES(448,'火','hi','ひ','ka','カ');
INSERT INTO all_kanji VALUES(449,'供','sona, tomo, sonae, sonaeru','そな、とも、そなえ、そなえる','kyou, ku','キョウ、ク');
INSERT INTO all_kanji VALUES(450,'彼','kare, kano','かれ、かの','hi','ヒ');
INSERT INTO all_kanji VALUES(451,'泣','na, naku','な、なく','kyuu','キュウ');
INSERT INTO all_kanji VALUES(452,'降','o, fu, oriru, orosu, furu, furi','お、ふ、おりる、おろす、ふる、ふり','kou','コウ');
INSERT INTO all_kanji VALUES(453,'晴','ha, hareru, hare, harasu','は、はれる、はれ、はらす','sei','セイ');
INSERT INTO all_kanji VALUES(454,'曇','kumo, kumoru, kumori','くも、くもる、くもり','don','ドン');
INSERT INTO all_kanji VALUES(455,'空','sora, a, kara, muna, aku, aki, akeru, kara, munashii, munashisa','そら、あ、から、むな、あく、あき、あける、から、むなしい、むなしさ','kuu','クウ');
INSERT INTO all_kanji VALUES(456,'夕','yuu','ゆう','seki','セキ');
INSERT INTO all_kanji VALUES(457,'準','n/a','','jun','ジュン');
INSERT INTO all_kanji VALUES(458,'備','sona, sonaeru, sonawaru','そな、そなえる、そなわる','bi','ビ');
INSERT INTO all_kanji VALUES(459,'三','mi, mikka, mittsu','み、みっか、みっつ','san','サン');
INSERT INTO all_kanji VALUES(460,'水','mizu','みず','sui','スイ');
INSERT INTO all_kanji VALUES(461,'歩','aru, ayu, aruku, ayumu, ayumi','ある、あゆ、あるく、あゆむ、あゆみ','ho, bu, fu','ホ、ブ、フ');
INSERT INTO all_kanji VALUES(462,'歌','uta, utau','うた、うたう','ka','カ');
INSERT INTO all_kanji VALUES(463,'足','ashi, ta, taru, tariru, tasu','あし、た、たる、たりる、たす','soku','ソク');
INSERT INTO all_kanji VALUES(464,'口','kuchi','くち','kou, ku','コウ、ク');
INSERT INTO all_kanji VALUES(465,'世','yo','よ','sei, se','セイ、セ');
INSERT INTO all_kanji VALUES(466,'界','n/a','','kai','カイ');
INSERT INTO all_kanji VALUES(467,'医','n/a','','i','イ');
INSERT INTO all_kanji VALUES(468,'者','mono','もの','sha','シャ');
INSERT INTO all_kanji VALUES(469,'配','kuba, kubaru','くば、くばる','hai','ハイ');
INSERT INTO all_kanji VALUES(470,'規','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(471,'木','ki, ko','き、こ','boku, moku','ボク、モク');
INSERT INTO all_kanji VALUES(472,'則','n/a','','soku','ソク');
INSERT INTO all_kanji VALUES(473,'正','tada, tadashii, tadasu, masa, masani','ただ、ただしい、ただす、まさ、まさに','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(474,'活','n/a','','katsu','カツ');
INSERT INTO all_kanji VALUES(475,'考','kanga, kangaeru, kangae','かんが、かんがえる、かんがえ','kou','コウ');
INSERT INTO all_kanji VALUES(476,'計','haka, hakaru, hakari, hakarau','はか、はかる、はかり、はからう','kei','ケイ');
INSERT INTO all_kanji VALUES(477,'奥','oku','おく','ou','オウ');
INSERT INTO all_kanji VALUES(478,'様','sama','さま','you','ヨウ');
INSERT INTO all_kanji VALUES(479,'眠','nemu, nemui, nemuru','ねむ、ねむい、ねむる','min','ミン');
INSERT INTO all_kanji VALUES(480,'外','soto, hoka, hazu, hazusu, hazureru','そと、ほか、はず、はずす、はずれる','gai, ge','ガイ、ゲ');
INSERT INTO all_kanji VALUES(481,'不','n/a','','fu, bu','フ、ブ');
INSERT INTO all_kanji VALUES(482,'金','kane, kana','かね、かな','kin, kon','キン、コン');
INSERT INTO all_kanji VALUES(483,'昔','mukashi','むかし','seki, shaku','セキ、シャク');
INSERT INTO all_kanji VALUES(484,'洋','n/a','','you','ヨウ');
INSERT INTO all_kanji VALUES(485,'寄','yo, yoru, yori, yoseru','よ、よる、より、よせる','ki','キ');
INSERT INTO all_kanji VALUES(486,'風','kaze, kaza','かぜ、かざ','fuu, fu','フウ、フ');
INSERT INTO all_kanji VALUES(487,'呼','yo, yobu','よ、よぶ','ko','コ');
INSERT INTO all_kanji VALUES(488,'怒','ika, oko, ikaru, okoru','いか、おこ、いかる、おこる','do','ド');
INSERT INTO all_kanji VALUES(489,'宿','yado, yadoru, yadosu','やど、やどる、やどす','shuku','シュク');
INSERT INTO all_kanji VALUES(490,'渡','wata, wataru, watasu','わた、わたる、わたす','to','ト');
INSERT INTO all_kanji VALUES(491,'旅','tabi','たび','ryo','リョ');
INSERT INTO all_kanji VALUES(492,'取','to, toru, tori','と、とる、とり','shu','シュ');
INSERT INTO all_kanji VALUES(493,'土','tsuchi','つち','do, to','ド、ト');
INSERT INTO all_kanji VALUES(494,'盗','nusu, nusumu, nusumi','ぬす、ぬすむ、ぬすみ','tou','トウ');
INSERT INTO all_kanji VALUES(495,'建','ta, tatsu, tateru, tate','た、たつ、たてる、たて','ken, kon','ケン、コン');
INSERT INTO all_kanji VALUES(496,'宅','n/a','','taku','タク');
INSERT INTO all_kanji VALUES(497,'申','mou, mousu, moushi','もう、もうす、もうし','shin','シン');
INSERT INTO all_kanji VALUES(498,'願','nega, negau','ねが、ねがう','gan','ガン');
INSERT INTO all_kanji VALUES(499,'主','nushi, omo, omoni, aruji','ぬし、おも、おもに、あるじ','shu, su','シュ、ス');
INSERT INTO all_kanji VALUES(500,'関','seki, kaka, kakawaru','せき、かか、かかわる','kan','カン');
INSERT INTO all_kanji VALUES(501,'特','n/a','','toku','トク');
INSERT INTO all_kanji VALUES(502,'別','waka, wakare, wakareru','わか、わかれ、わかれる','betsu','ベツ');
INSERT INTO all_kanji VALUES(503,'僕','n/a','','boku','ボク');
INSERT INTO all_kanji VALUES(504,'日','hi, ka','ひ、か','nichi, jitsu','ニチ、ジツ');
INSERT INTO all_kanji VALUES(505,'予','n/a','','yo','ヨ');
INSERT INTO all_kanji VALUES(506,'定','sada, sadaka, sadameru, sadamaru','さだ、さだか、さだめる、さだまる','tei, jou','テイ、ジョウ');
INSERT INTO all_kanji VALUES(507,'写','utsu, utsusu, utsuru','うつ、うつす、うつる','sha','シャ');
INSERT INTO all_kanji VALUES(508,'真','ma','ま','shin','シン');
INSERT INTO all_kanji VALUES(509,'普','n/a','','fu','フ');
INSERT INTO all_kanji VALUES(510,'意','n/a','','i','イ');
INSERT INTO all_kanji VALUES(511,'忘','wasu, wasureru','わす、わすれる','bou','ボウ');
INSERT INTO all_kanji VALUES(512,'覚','obo, sa, oboeru, samasu, sameru','おぼ、さ、おぼえる、さます、さめる','kaku','カク');
INSERT INTO all_kanji VALUES(513,'席','n/a','','seki','セキ');
INSERT INTO all_kanji VALUES(514,'君','kimi','きみ','kun','クン');
INSERT INTO all_kanji VALUES(515,'百','n/a','','hyaku','ヒャク');
INSERT INTO all_kanji VALUES(516,'熱','atsu, atsui','あつ、あつい','netsu','ネツ');
INSERT INTO all_kanji VALUES(517,'死','shi, shinu, shini','し、しぬ、しに','shi','シ');
INSERT INTO all_kanji VALUES(518,'結','musu, yu, musubu, yuu, yuwaeru','むす、ゆ、むすぶ、ゆう、ゆわえる','ketsu','ケツ');
INSERT INTO all_kanji VALUES(519,'婚','n/a','','kon','コン');
INSERT INTO all_kanji VALUES(520,'式','n/a','','shiki','シキ');
INSERT INTO all_kanji VALUES(521,'牛','ushi','うし','gyuu','ギュウ');
INSERT INTO all_kanji VALUES(522,'乳','chichi, chi','ちち、ち','nyuu','ニュウ');
INSERT INTO all_kanji VALUES(523,'沢','sawa','さわ','taku','タク');
INSERT INTO all_kanji VALUES(524,'町','machi','まち','chou','チョウ');
INSERT INTO all_kanji VALUES(525,'他','n/a','','ta','タ');
INSERT INTO all_kanji VALUES(526,'千','chi','ち','sen','セン');
INSERT INTO all_kanji VALUES(527,'飯','meshi','めし','han','ハン');
INSERT INTO all_kanji VALUES(528,'答','kota, kotae, kotaeru','こた、こたえ、こたえる','tou','トウ');
INSERT INTO all_kanji VALUES(529,'店','mise','みせ','ten','テン');
INSERT INTO all_kanji VALUES(530,'愛','ito, itoshii, itooshimu','いと、いとしい、いとおしむ','ai','アイ');
INSERT INTO all_kanji VALUES(531,'合','a, au, ai, awasu, awaseru','あ、あう、あい、あわす、あわせる','gou, ka, ga','ゴウ、カ、ガ');
INSERT INTO all_kanji VALUES(532,'悲','kana, kanashii, kanashimu, kanashisa, kanashimi','かな、かなしい、かなしむ、かなしさ、かなしみ','hi','ヒ');
INSERT INTO all_kanji VALUES(533,'職','n/a','','shoku','ショク');
INSERT INTO all_kanji VALUES(534,'員','n/a','','in','イン');
INSERT INTO all_kanji VALUES(535,'幸','saiwa, saiwai, sachi, shiawa, shiawase','さいわ、さいわい、さち、しあわ、しあわせ','kou','コウ');
INSERT INTO all_kanji VALUES(536,'飛','to, tobu, tobasu','と、とぶ、とばす','hi','ヒ');
INSERT INTO all_kanji VALUES(537,'今','ima','いま','kon, kin','コン、キン');
INSERT INTO all_kanji VALUES(538,'耳','mimi','みみ','ji','ジ');
INSERT INTO all_kanji VALUES(539,'嫌','kira, kirau, kirai, iya, iyagaru','きら、きらう、きらい、いや、いやがる','ken','ケン');
INSERT INTO all_kanji VALUES(540,'窓','mado','まど','sou','ソウ');
INSERT INTO all_kanji VALUES(541,'喜','yoroko, yorokobu, yorokobi, yorokobasu','よろこ、よろこぶ、よろこび、よろこばす','ki','キ');
INSERT INTO all_kanji VALUES(542,'反','so, soru, sorasu','そ、そる、そらす','han, hon, tan','ハン、ホン、タン');
INSERT INTO all_kanji VALUES(543,'対','n/a','','tai, tsui','タイ、ツイ');
INSERT INTO all_kanji VALUES(544,'恋','ko, kou, koi, koishii, koisuru','こ、こう、こい、こいしい、こいする','ren','レン');
INSERT INTO all_kanji VALUES(545,'告','tsu, tsugu, tsugeru','つ、つぐ、つげる','koku','コク');
INSERT INTO all_kanji VALUES(546,'許','yuru, yurusu, yurushi','ゆる、ゆるす、ゆるし','kyo','キョ');
INSERT INTO all_kanji VALUES(547,'件','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(548,'小','chii, chiisai, ko, o','ちい、ちいさい、こ、お','shou','ショウ');
INSERT INTO all_kanji VALUES(549,'戻','modo, modosu, modoru','もど、もどす、もどる','rei','レイ');
INSERT INTO all_kanji VALUES(550,'服','n/a','','fuku','フク');
INSERT INTO all_kanji VALUES(551,'曜','n/a','','you','ヨウ');
INSERT INTO all_kanji VALUES(552,'品','shina','しな','hin','ヒン');
INSERT INTO all_kanji VALUES(553,'未','ima, ma, imada, mada','いま、ま、いまだ、まだ','mi','ミ');
INSERT INTO all_kanji VALUES(554,'完','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(555,'海','umi','うみ','kai','カイ');
INSERT INTO all_kanji VALUES(556,'島','shima','しま','tou','トウ');
INSERT INTO all_kanji VALUES(557,'級','n/a','','kyuu','キュウ');
INSERT INTO all_kanji VALUES(558,'顔','kao','かお','gan','ガン');
INSERT INTO all_kanji VALUES(559,'休','yasu, yasumu, yasumi, yasumeru','やす、やすむ、やすみ、やすめる','kyuu','キュウ');
INSERT INTO all_kanji VALUES(560,'面','omo, omote, tsura','おも、おもて、つら','men','メン');
INSERT INTO all_kanji VALUES(561,'企','kuwada, kuwadateru','くわだ、くわだてる','ki','キ');
INSERT INTO all_kanji VALUES(562,'市','ichi','いち','shi','シ');
INSERT INTO all_kanji VALUES(563,'頼','tano, tanomu, tanomoshii, tayo, tayoru','たの、たのむ、たのもしい、たよ、たよる','rai','ライ');
INSERT INTO all_kanji VALUES(564,'第','n/a','','dai','ダイ');
INSERT INTO all_kanji VALUES(565,'表','omote, arawa, arawasu, arawareru','おもて、あらわ、あらわす、あらわれる','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(566,'将','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(567,'希','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(568,'場','ba','ば','jou','ジョウ');
INSERT INTO all_kanji VALUES(569,'査','n/a','','sa','サ');
INSERT INTO all_kanji VALUES(570,'学','mana, manabu','まな、まなぶ','gaku','ガク');
INSERT INTO all_kanji VALUES(571,'行','i, iku, yu, yuku, okona, okonau','い、いく、ゆ、ゆく、おこな、おこなう','kou, gyou, an','コウ、ギョウ、アン');
INSERT INTO all_kanji VALUES(572,'係','kaka, kakaru, kakari, kakawaru, kakawari','かか、かかる、かかり、かかわる、かかわり','kei','ケイ');
INSERT INTO all_kanji VALUES(573,'訳','wake','わけ','yaku','ヤク');
INSERT INTO all_kanji VALUES(574,'課','n/a','','ka','カ');
INSERT INTO all_kanji VALUES(575,'続','tsuzu, tsuzuku, tsuzukeru, tsuzuki','つづ、つづく、つづける、つづき','zoku','ゾク');
INSERT INTO all_kanji VALUES(576,'際','kiwa','きわ','sai','サイ');
INSERT INTO all_kanji VALUES(577,'望','nozo, nozomu, nozomi','のぞ、のぞむ、のぞみ','bou, mou','ボウ、モウ');
INSERT INTO all_kanji VALUES(578,'成','na, naru, nasu','な、なる、なす','sei, jou','セイ、ジョウ');
INSERT INTO all_kanji VALUES(579,'功','n/a','','kou, ku','コウ、ク');
INSERT INTO all_kanji VALUES(580,'約','n/a','','yaku','ヤク');
INSERT INTO all_kanji VALUES(581,'束','taba, tabaneru','たば、たばねる','soku','ソク');
INSERT INTO all_kanji VALUES(582,'家','ie, ya','いえ、や','ka, ke','カ、ケ');
INSERT INTO all_kanji VALUES(583,'受','u, ukeru, ukaru','う、うける、うかる','ju','ジュ');
INSERT INTO all_kanji VALUES(584,'有','a, aru','あ、ある','yuu, u','ユウ、ウ');
INSERT INTO all_kanji VALUES(585,'点','n/a','','ten','テン');
INSERT INTO all_kanji VALUES(586,'識','n/a','','shiki','シキ');
INSERT INTO all_kanji VALUES(587,'感','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(588,'送','oku, okuru','おく、おくる','sou','ソウ');
INSERT INTO all_kanji VALUES(589,'数','kazu, kazo, kazoeru','かず、かぞ、かぞえる','suu, su','スウ、ス');
INSERT INTO all_kanji VALUES(590,'球','tama','たま','kyuu','キュウ');
INSERT INTO all_kanji VALUES(591,'遊','aso, asobi, asobu','あそ、あそび、あそぶ','yuu, yu','ユウ、ユ');
INSERT INTO all_kanji VALUES(592,'招','mane, maneku, maneki','まね、まねく、まねき','shou','ショウ');
INSERT INTO all_kanji VALUES(593,'帰','kae, kaeru','かえ、かえる','ki','キ');
INSERT INTO all_kanji VALUES(594,'選','era, erabu','えら、えらぶ','sen','セン');
INSERT INTO all_kanji VALUES(595,'講','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(596,'義','n/a','','gi','ギ');
INSERT INTO all_kanji VALUES(597,'役','n/a','','yaku, eki','ヤク、エキ');
INSERT INTO all_kanji VALUES(598,'立','ta, tate, tatsu, tachi, tateru','た、たて、たつ、たち、たてる','ritsu, ryuu','リツ、リュウ');
INSERT INTO all_kanji VALUES(599,'論','n/a','','ron','ロン');
INSERT INTO all_kanji VALUES(600,'基','moto, motoi','もと、もとい','ki','キ');
INSERT INTO all_kanji VALUES(601,'厚','atsu, atsui','あつ、あつい','kou','コウ');
INSERT INTO all_kanji VALUES(602,'勧','susu, susumeru','すす、すすめる','kan','カン');
INSERT INTO all_kanji VALUES(603,'般','n/a','','han','ハン');
INSERT INTO all_kanji VALUES(604,'近','chika, chikai, chikaku','ちか、ちかい、ちかく','kin','キン');
INSERT INTO all_kanji VALUES(605,'養','yashina, yashinau','やしな、やしなう','you','ヨウ');
INSERT INTO all_kanji VALUES(606,'化','ba, bakeru, bakasu','ば、ばける、ばかす','ka, ke','カ、ケ');
INSERT INTO all_kanji VALUES(607,'科','n/a','','ka','カ');
INSERT INTO all_kanji VALUES(608,'績','n/a','','seki','セキ');
INSERT INTO all_kanji VALUES(609,'型','kata','かた','kei','ケイ');
INSERT INTO all_kanji VALUES(610,'苦','kuru, niga, kurushii, kurushimu, kurushimeru, nigai, nigaru','くる、にが、くるしい、くるしむ、くるしめる、にがい、にがる','ku','ク');
INSERT INTO all_kanji VALUES(611,'満','mi, michiru, mitsu, mitasu','み、みちる、みつ、みたす','man','マン');
INSERT INTO all_kanji VALUES(612,'増','ma, fu, masu, mashi, fueru, fuyasu','ま、ふ、ます、まし、ふえる、ふやす','zou','ゾウ');
INSERT INTO all_kanji VALUES(613,'声','koe, kowa','こえ、こわ','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(614,'現','arawa, arawareru, arawasu','あらわ、あらわれる、あらわす','gen','ゲン');
INSERT INTO all_kanji VALUES(615,'父','chichi','ちち','fu','フ');
INSERT INTO all_kanji VALUES(616,'在','a, aru','あ、ある','zai','ザイ');
INSERT INTO all_kanji VALUES(617,'夢','yume','ゆめ','mu','ム');
INSERT INTO all_kanji VALUES(618,'乗','no, noru, nori, noseru','の、のる、のり、のせる','jou','ジョウ');
INSERT INTO all_kanji VALUES(619,'放','hana, hanasu, hanatsu, hanareru','はな、はなす、はなつ、はなれる','hou','ホウ');
INSERT INTO all_kanji VALUES(620,'協','n/a','','kyou','キョウ');
INSERT INTO all_kanji VALUES(621,'力','chikara','ちから','ryoku, riki','リョク、リキ');
INSERT INTO all_kanji VALUES(622,'賛','n/a','','san','サン');
INSERT INTO all_kanji VALUES(623,'説','to, toku','と、とく','setsu, zei','セツ、ゼイ');
INSERT INTO all_kanji VALUES(624,'落','o, ochiru, otosu','お、おちる、おとす','raku','ラク');
INSERT INTO all_kanji VALUES(625,'名','na','な','mei, myou','メイ、ミョウ');
INSERT INTO all_kanji VALUES(626,'母','haha','はは','bo','ボ');
INSERT INTO all_kanji VALUES(627,'機','hata','はた','ki','キ');
INSERT INTO all_kanji VALUES(628,'具','n/a','','gu','グ');
INSERT INTO all_kanji VALUES(629,'詳','kuwa, kuwashii','くわ、くわしい','shou','ショウ');
INSERT INTO all_kanji VALUES(630,'解','to, toku, takasu, tokeru','と、とく、とかす、とける','kai, ge','カイ、ゲ');
INSERT INTO all_kanji VALUES(631,'構','kama, kamaeru, kamau','かま、かまえる、かまう','kou','コウ');
INSERT INTO all_kanji VALUES(632,'情','nasa, nasake','なさ、なさけ','jou, sei','ジョウ、セイ');
INSERT INTO all_kanji VALUES(633,'共','tomo','とも','kyou','キョウ');
INSERT INTO all_kanji VALUES(634,'存','n/a','','son, zon','ソン、ゾン');
INSERT INTO all_kanji VALUES(635,'静','shizu, shizuka, shizumaru, shizumeru','しず、しずか、しずまる、しずめる','sei, jou','セイ、ジョウ');
INSERT INTO all_kanji VALUES(636,'流','naga, nagareru, nagare, nagasu','なが、ながれる、ながれ、ながす','ryuu, ru','リュウ、ル');
INSERT INTO all_kanji VALUES(637,'兄','ani','あに','kei, kyou','ケイ、キョウ');
INSERT INTO all_kanji VALUES(638,'芸','n/a','','gei','ゲイ');
INSERT INTO all_kanji VALUES(639,'術','n/a','','jutsu','ジュツ');
INSERT INTO all_kanji VALUES(640,'光','hika, hikaru, hikari','ひか、ひかる、ひかり','kou','コウ');
INSERT INTO all_kanji VALUES(641,'景','n/a','','kei','ケイ');
INSERT INTO all_kanji VALUES(642,'驚','odoro, odoroku, odorokasu','おどろ、おどろく、おどろかす','kyou','キョウ');
INSERT INTO all_kanji VALUES(643,'助','tasu, tasukeru, tasukaru, suke','たす、たすける、たすかる、すけ','jo','ジョ');
INSERT INTO all_kanji VALUES(644,'求','moto, motomeru','もと、もとめる','kyuu','キュウ');
INSERT INTO all_kanji VALUES(645,'留','to, todo, tomeru, tomaru, todomaru, todomeru','と、とど、とめる、とまる、とどまる、とどめる','ryuu, ru','リュウ、ル');
INSERT INTO all_kanji VALUES(646,'興','oko, okoru, okosu','おこ、おこる、おこす','kou, kyou','コウ、キョウ');
INSERT INTO all_kanji VALUES(647,'深','fuka, fukai, fukamaru, fukameru','ふか、ふかい、ふかまる、ふかめる','shin','シン');
INSERT INTO all_kanji VALUES(648,'弟','otouto','おとうと','tei, dai, de','テイ、ダイ、デ');
INSERT INTO all_kanji VALUES(649,'猫','neko','ねこ','byou','ビョウ');
INSERT INTO all_kanji VALUES(650,'想','n/a','','sou, so','ソウ、ソ');
INSERT INTO all_kanji VALUES(651,'像','n/a','','zou','ゾウ');
INSERT INTO all_kanji VALUES(652,'平','tai, hiratai, taira, hira','たい、ひらたい、たいら、ひら','hei, byou','ヘイ、ビョウ');
INSERT INTO all_kanji VALUES(653,'位','kurai','くらい','i','イ');
INSERT INTO all_kanji VALUES(654,'置','o, oku','お、おく','chi','チ');
INSERT INTO all_kanji VALUES(655,'進','susu, susumu, susumeru','すす、すすむ、すすめる','shin','シン');
INSERT INTO all_kanji VALUES(656,'越','ko, kosu, koeru','こ、こす、こえる','etsu','エツ');
INSERT INTO all_kanji VALUES(657,'庭','niwa','にわ','tei','テイ');
INSERT INTO all_kanji VALUES(658,'勢','ikio, ikioi','いきお、いきおい','sei','セイ');
INSERT INTO all_kanji VALUES(659,'姉','ane','あね','shi','シ');
INSERT INTO all_kanji VALUES(660,'性','n/a','','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(661,'団','n/a','','dan, ton','ダン、トン');
INSERT INTO all_kanji VALUES(662,'弁','n/a','','ben','ベン');
INSERT INTO all_kanji VALUES(663,'護','mamo, mamoru','まも、まもる','go','ゴ');
INSERT INTO all_kanji VALUES(664,'条','n/a','','jou','ジョウ');
INSERT INTO all_kanji VALUES(665,'影','kage','かげ','ei','エイ');
INSERT INTO all_kanji VALUES(666,'響','hibi, hibiku, hibiki, hibikasu','ひび、ひびく、ひびき、ひびかす','kyou','キョウ');
INSERT INTO all_kanji VALUES(667,'訪','otozureru, tazuneru, otozu, tazu','おとずれる、たずねる、おとず、たず','hou','ホウ');
INSERT INTO all_kanji VALUES(668,'参','mairu, mai','まいる、まい','san','サン');
INSERT INTO all_kanji VALUES(669,'御','on','おん','gyo, go','ギョ、ゴ');
INSERT INTO all_kanji VALUES(670,'妹','imouto','いもうと','mai','マイ');
INSERT INTO all_kanji VALUES(671,'果','hatasu, hateru, hate, ha','はたす、はてる、はて、は','ka','カ');
INSERT INTO all_kanji VALUES(672,'慣','nareru, narasu, na','なれる、ならす、な','kan','カン');
INSERT INTO all_kanji VALUES(673,'専','moppara, moppa','もっぱら、もっぱ','sen','セン');
INSERT INTO all_kanji VALUES(674,'攻','semeru, se','せめる、せ','kou','コウ');
INSERT INTO all_kanji VALUES(675,'趣','omomuki','おもむき','shu','シュ');
INSERT INTO all_kanji VALUES(676,'賞','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(677,'誌','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(678,'復','n/a','','fuku','フク');
INSERT INTO all_kanji VALUES(679,'限','kagiru, kagiri, kagi','かぎる、かぎり、かぎ','gen','ゲン');
INSERT INTO all_kanji VALUES(680,'確','tashika, tashikameru, tashi','たしか、たしかめる、たし','kaku','カク');
INSERT INTO all_kanji VALUES(681,'院','n/a','','in','イン');
INSERT INTO all_kanji VALUES(682,'来','ku, kuru, kita, kitaru','く、くる、きた、きたる','rai','ライ');
INSERT INTO all_kanji VALUES(683,'保','tamotsu, tamo','たもつ、たも','ho','ホ');
INSERT INTO all_kanji VALUES(684,'証','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(685,'追','ou, o','おう、お','tsui','ツイ');
INSERT INTO all_kanji VALUES(686,'便','tayori, tayo','たより、たよ','bin, ben','ビン、ベン');
INSERT INTO all_kanji VALUES(687,'著','arawasu, ichijirushii, arawa, ichijiru','あらわす、いちじるしい、あらわ、いちじる','cho','チョ');
INSERT INTO all_kanji VALUES(688,'代','kawaru, kawari, kaeru, yo, shiro, ka','かわる、かわり、かえる、よ、しろ、か','dai, tai','ダイ、タイ');
INSERT INTO all_kanji VALUES(689,'抜','nuku, nuki, nukeru, nukasu, nukaru, nu','ぬく、ぬき、ぬける、ぬかす、ぬかる、ぬ','batsu','バツ');
INSERT INTO all_kanji VALUES(690,'肩','kata','かた','ken','ケン');
INSERT INTO all_kanji VALUES(691,'伺','ukagau, ukagai, ukaga','うかがう、うかがい、うかが','shi','シ');
INSERT INTO all_kanji VALUES(692,'材','n/a','','zai','ザイ');
INSERT INTO all_kanji VALUES(693,'起','o, okiru, okosu','お、おきる、おこす','ki','キ');
INSERT INTO all_kanji VALUES(694,'残','nokoru, nokosu, nokori, noko','のこる、のこす、のこり、のこ','zan','ザン');
INSERT INTO all_kanji VALUES(695,'念','n/a','','nen','ネン');
INSERT INTO all_kanji VALUES(696,'恥','ha, haji, hajirau, hajirai, hajiru, hazukashii','は、はじ、はじらう、はじらい、はじる、はずかしい','chi','チ');
INSERT INTO all_kanji VALUES(697,'都','miyako','みやこ','to, tsu','ト、ツ');
INSERT INTO all_kanji VALUES(698,'洗','arau, ara','あらう、あら','sen','セン');
INSERT INTO all_kanji VALUES(699,'州','su','す','shuu','シュウ');
INSERT INTO all_kanji VALUES(700,'福','n/a','','fuku','フク');
INSERT INTO all_kanji VALUES(701,'側','kawa','かわ','soku','ソク');
INSERT INTO all_kanji VALUES(702,'恐','osoreru, osoru, osoroshii, oso','おそれる、おそる、おそろしい、おそ','kyou','キョウ');
INSERT INTO all_kanji VALUES(703,'敗','yabureru, yabu','やぶれる、やぶ','hai','ハイ');
INSERT INTO all_kanji VALUES(704,'毎','goto','ごと','mai','マイ');
INSERT INTO all_kanji VALUES(705,'比','kuraberu, kura','くらべる、くら','hi','ヒ');
INSERT INTO all_kanji VALUES(706,'倍','n/a','','bai','バイ');
INSERT INTO all_kanji VALUES(707,'詩','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(708,'素','n/a','','so, su','ソ、ス');
INSERT INTO all_kanji VALUES(709,'胸','mune, muna','むね、むな','kyou','キョウ');
INSERT INTO all_kanji VALUES(710,'打','utsu, uchi','うつ、うち','da','ダ');
INSERT INTO all_kanji VALUES(711,'厳','ogosoka, kibishii, ogoso, kibi','おごそか、きびしい、おごそ、きび','gen, gon','ゲン、ゴン');
INSERT INTO all_kanji VALUES(712,'優','yasashi, yasashisa, sugureru, yasa, sugu','やさし、やさしさ、すぐれる、やさ、すぐ','yuu','ユウ');
INSERT INTO all_kanji VALUES(713,'可','n/a','','ka','カ');
INSERT INTO all_kanji VALUES(714,'形','kata, katachi','かた、かたち','kei, gyou','ケイ、ギョウ');
INSERT INTO all_kanji VALUES(715,'朝','asa','あさ','chou','チョウ');
INSERT INTO all_kanji VALUES(716,'詞','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(717,'程','hodo','ほど','tei','テイ');
INSERT INTO all_kanji VALUES(718,'命','inochi','いのち','mei, myou','メイ、ミョウ');
INSERT INTO all_kanji VALUES(719,'令','n/a','','rei','レイ');
INSERT INTO all_kanji VALUES(720,'容','n/a','','you','ヨウ');
INSERT INTO all_kanji VALUES(721,'議','n/a','','gi','ギ');
INSERT INTO all_kanji VALUES(722,'印','shirushi','しるし','in','イン');
INSERT INTO all_kanji VALUES(723,'象','n/a','','shou, zou','ショウ、ゾウ');
INSERT INTO all_kanji VALUES(724,'句','n/a','','ku','ク');
INSERT INTO all_kanji VALUES(725,'線','n/a','','sen','セン');
INSERT INTO all_kanji VALUES(726,'晩','n/a','','ban','バン');
INSERT INTO all_kanji VALUES(727,'輩','n/a','','hai','ハイ');
INSERT INTO all_kanji VALUES(728,'倒','taoreru, taosu, tao','たおれる、たおす、たお','tou','トウ');
INSERT INTO all_kanji VALUES(729,'応','n/a','','ou, nou','オウ、ノウ');
INSERT INTO all_kanji VALUES(730,'募','tsunoru','つのる','bo','ボ');
INSERT INTO all_kanji VALUES(731,'制','n/a','','sei','セイ');
INSERT INTO all_kanji VALUES(732,'量','hakaru, hakari, haka','はかる、はかり、はか','ryou','リョウ');
INSERT INTO all_kanji VALUES(733,'各','onoono','おのおの','kaku','カク');
INSERT INTO all_kanji VALUES(734,'評','n/a','','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(735,'判','n/a','','han, ban','ハン、バン');
INSERT INTO all_kanji VALUES(736,'換','kaeru, kawaru, ka','かえる、かわる、か','kan','カン');
INSERT INTO all_kanji VALUES(737,'族','n/a','','zoku','ゾク');
INSERT INTO all_kanji VALUES(738,'競','kisou, seru, kiso, se','きそう、せる、きそ、せ','kyou, kei','キョウ、ケイ');
INSERT INTO all_kanji VALUES(739,'争','arasou, arasoi, araso','あらそう、あらそい、あらそ','sou','ソウ');
INSERT INTO all_kanji VALUES(740,'率','hikiiru, hiki','ひきいる、ひき','sotsu, ritsu','ソツ、リツ');
INSERT INTO all_kanji VALUES(741,'得','eru, uru, e, u','える、うる、え、う','toku','トク');
INSERT INTO all_kanji VALUES(742,'張','haru, hari, ha','はる、はり、は','chou','チョウ');
INSERT INTO all_kanji VALUES(743,'価','atai','あたい','ka','カ');
INSERT INTO all_kanji VALUES(744,'抑','osaeru, osa','おさえる、おさ','yoku','ヨク');
INSERT INTO all_kanji VALUES(745,'弱','yowai, yowaru, yowamaru, yowameru, yowa','よわい、よわる、よわまる、よわめる、よわ','jaku','ジャク');
INSERT INTO all_kanji VALUES(746,'技','waza','わざ','gi','ギ');
INSERT INTO all_kanji VALUES(747,'律','n/a','','ritsu, richi','リツ、リチ');
INSERT INTO all_kanji VALUES(748,'勉','n/a','','ben','ベン');
INSERT INTO all_kanji VALUES(749,'尊','tattoi, tattobu, toutoi, toutobu, tatto, touto','たっとい、たっとぶ、とうとい、とうとぶ、たっと、とうと','son','ソン');
INSERT INTO all_kanji VALUES(750,'敬','uyamau, uyamai, uyama','うやまう、うやまい、うやま','kei','ケイ');
INSERT INTO all_kanji VALUES(751,'観','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(752,'種','tane','たね','shu','シュ');
INSERT INTO all_kanji VALUES(753,'能','n/a','','nou','ノウ');
INSERT INTO all_kanji VALUES(754,'延','nobiru, noberu, nobe, nobasu, no','のびる、のべる、のべ、のばす、の','en','エン');
INSERT INTO all_kanji VALUES(755,'薬','kusuri','くすり','yaku','ヤク');
INSERT INTO all_kanji VALUES(756,'笑','wara, e, warau, warai, emu, emi','わら、え、わらう、わらい、えむ、えみ','shou','ショウ');
INSERT INTO all_kanji VALUES(757,'非','n/a','','hi','ヒ');
INSERT INTO all_kanji VALUES(758,'常','tsune, toko','つね、とこ','jou','ジョウ');
INSERT INTO all_kanji VALUES(759,'強','tsuyo, tsuyoi, tsuyomeru, tsuyomaru, shi, shiiru','つよ、つよい、つよめる、つよまる、し、しいる','kyou, gou','キョウ、ゴウ');
INSERT INTO all_kanji VALUES(760,'客','n/a','','kyaku, kaku','キャク、カク');
INSERT INTO all_kanji VALUES(761,'届','todo, todoku, todokeru','とど、とどく、とどける','n/a','');
INSERT INTO all_kanji VALUES(762,'舎','n/a','','sha','シャ');
INSERT INTO all_kanji VALUES(763,'暮','ku, kureru, kurasu','く、くれる、くらす','bo','ボ');
INSERT INTO all_kanji VALUES(764,'怖','kowa, kowai, kowagaru','こわ、こわい、こわがる','fu','フ');
INSERT INTO all_kanji VALUES(765,'息','iki','いき','soku','ソク');
INSERT INTO all_kanji VALUES(766,'拾','hiro, hirou','ひろ、ひろう','shuu, juu','シュウ、ジュウ');
INSERT INTO all_kanji VALUES(767,'段','n/a','','dan','ダン');
INSERT INTO all_kanji VALUES(768,'暇','hima','ひま','ka','カ');
INSERT INTO all_kanji VALUES(769,'預','azu, azukeru, azukaru','あず、あずける、あずかる','yo','ヨ');
INSERT INTO all_kanji VALUES(770,'昨','n/a','','saku','サク');
INSERT INTO all_kanji VALUES(771,'断','ta, korowa, tatsu, kotowaru, kotowari','た、ことわ、たつ、ことわる、ことわり','dan','ダン');
INSERT INTO all_kanji VALUES(772,'承','uketamawa, uketamawaru','うけたまわ、うけたまわる','shou','ショウ');
INSERT INTO all_kanji VALUES(773,'丸','maru, marui, marumeru','まる、まるい、まるめる','gan','ガン');
INSERT INTO all_kanji VALUES(774,'謝','ayamaru, ayama','あやまる、あやま','sha','シャ');
INSERT INTO all_kanji VALUES(775,'敵','kataki','かたき','teki','テキ');
INSERT INTO all_kanji VALUES(776,'坊','n/a','','bou, bot','ボウ、ボツ');
INSERT INTO all_kanji VALUES(777,'岸','kishi','きし','gan','ガン');
INSERT INTO all_kanji VALUES(778,'良','yo, i, yoi, ii','よ、い、よい、いい','ryou','リョウ');
INSERT INTO all_kanji VALUES(779,'散','chi, chiru, chirasu, chirakasu, chirakaru, chirabaru, chirabasu','ち、ちる、ちらす、ちらかす、ちらかる、ちらばる、ちらばす','san','サン');
INSERT INTO all_kanji VALUES(780,'訓','n/a','','kun','クン');
INSERT INTO all_kanji VALUES(781,'食','ku, kuu, ta, taberu','く、くう、た、たべる','shoku, jiki','ショク、ジキ');
INSERT INTO all_kanji VALUES(782,'支','sasa, sasaeru','ささ、ささえる','shi','シ');
INSERT INTO all_kanji VALUES(783,'組','ku, kumu, kumi','く、くむ、くみ','so','ソ');
INSERT INTO all_kanji VALUES(784,'守','mamo, mori, mamoru, mamori','まも、もり、まもる、まもり','shu, su','シュ、ス');
INSERT INTO all_kanji VALUES(785,'消','ki, ke, kieru, kesu','き、け、きえる、けす','shou','ショウ');
INSERT INTO all_kanji VALUES(786,'商','akina, akinau, akinai','あきな、あきなう、あきない','shou','ショウ');
INSERT INTO all_kanji VALUES(787,'似','niru, ni','にる、に','ji','ジ');
INSERT INTO all_kanji VALUES(788,'冒','oka, okasu','おか、おかす','bou','ボウ');
INSERT INTO all_kanji VALUES(789,'険','kewa, kewashii','けわ、けわしい','ken','ケン');
INSERT INTO all_kanji VALUES(790,'捨','su, suteru','す、すてる','sha','シャ');
INSERT INTO all_kanji VALUES(791,'状','n/a','','jou','ジョウ');
INSERT INTO all_kanji VALUES(792,'年','toshi','とし','nen','ネン');
INSERT INTO all_kanji VALUES(793,'作','tsuku, tsukuru, tsukuri','つく、つくる、つくり','saku, sa','サク、サ');
INSERT INTO all_kanji VALUES(794,'態','n/a','','tai','タイ');
INSERT INTO all_kanji VALUES(795,'勇','isa, isamu, isamashii','いさ、いさむ、いさましい','yuu','ユウ');
INSERT INTO all_kanji VALUES(796,'敢','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(797,'派','n/a','','ha','ハ');
INSERT INTO all_kanji VALUES(798,'再','futata, futatabi','ふたた、ふたたび','sai, sa','サイ、サ');
INSERT INTO all_kanji VALUES(799,'与','ata, ataeru','あた、あたえる','yo','ヨ');
INSERT INTO all_kanji VALUES(800,'案','n/a','','an','アン');
INSERT INTO all_kanji VALUES(801,'美','utsuku, utsukushii','うつく、うつくしい','bi','ビ');
INSERT INTO all_kanji VALUES(802,'絵','n/a','','kai, e','カイ、エ');
INSERT INTO all_kanji VALUES(803,'農','n/a','','nou','ノウ');
INSERT INTO all_kanji VALUES(804,'読','yo, yomu','よ、よむ','doku, toku, tou','ドク、トク、トウ');
INSERT INTO all_kanji VALUES(805,'描','ega, egaku','えが、えがく','byou','ビョウ');
INSERT INTO all_kanji VALUES(806,'徒','n/a','','to','ト');
INSERT INTO all_kanji VALUES(807,'城','shiro','しろ','jou','ジョウ');
INSERT INTO all_kanji VALUES(808,'激','hage, hageshii','はげ、はげしい','geki','ゲキ');
INSERT INTO all_kanji VALUES(809,'異','koto, kotonaru','こと、ことなる','i','イ');
INSERT INTO all_kanji VALUES(810,'総','n/a','','sou','ソウ');
INSERT INTO all_kanji VALUES(811,'注','soso, sosogu','そそ、そそぐ','chuu','チュウ');
INSERT INTO all_kanji VALUES(812,'改','arata, aratameru, aratamaru','あらた、あらためる、あらたまる','kai','カイ');
INSERT INTO all_kanji VALUES(813,'革','kawa','かわ','kaku','カク');
INSERT INTO all_kanji VALUES(814,'任','maka, makaseru, makasu','まか、まかせる、まかす','nin','ニン');
INSERT INTO all_kanji VALUES(815,'週','n/a','','shuu','シュウ');
INSERT INTO all_kanji VALUES(816,'抗','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(817,'身','mi','み','shin','シン');
INSERT INTO all_kanji VALUES(818,'門','kado','かど','mon','モン');
INSERT INTO all_kanji VALUES(819,'禁','n/a','','kin','キン');
INSERT INTO all_kanji VALUES(820,'根','ne','ね','kon','コン');
INSERT INTO all_kanji VALUES(821,'提','sageru, sa','さげる、さ','tei','テイ');
INSERT INTO all_kanji VALUES(822,'稲','ine, ina','いね、いな','tou','トウ');
INSERT INTO all_kanji VALUES(823,'耕','tagaya, tagayasu','たがや、たがやす','kou','コウ');
INSERT INTO all_kanji VALUES(824,'営','itona, itonamu, itonami','いとな、いとなむ、いとなみ','ei','エイ');
INSERT INTO all_kanji VALUES(825,'展','n/a','','ten','テン');
INSERT INTO all_kanji VALUES(826,'回','mawa, mawaru, mawasu','まわ、まわる、まわす','kai, e','カイ、エ');
INSERT INTO all_kanji VALUES(827,'疑','utaga, utagau, utagai','うたが、うたがう、うたがい','gi','ギ');
INSERT INTO all_kanji VALUES(828,'漁','n/a','','gyo, ryou','ギョ、リョウ');
INSERT INTO all_kanji VALUES(829,'突','tsu, tsuku','つ、つく','totsu','トツ');
INSERT INTO all_kanji VALUES(830,'批','n/a','','hi','ヒ');
INSERT INTO all_kanji VALUES(831,'端','hashi, ha, hata','はし、は、はた','tan','タン');
INSERT INTO all_kanji VALUES(832,'列','n/a','','retsu','レツ');
INSERT INTO all_kanji VALUES(833,'即','sunawa, sunawachi','すなわ、すなわち','soku','ソク');
INSERT INTO all_kanji VALUES(834,'指','yubi, sa, sasu','ゆび、さ、さす','shi','シ');
INSERT INTO all_kanji VALUES(835,'値','ne, atai','ね、あたい','chi','チ');
INSERT INTO all_kanji VALUES(836,'熟','u, ureru','う、うれる','juku','ジュク');
INSERT INTO all_kanji VALUES(837,'明','a, akeru, aka, akarui, akaramu, aki, akiraka','あ、あける、あか、あかるい、あからむ、あき、あきらか','mei, myou','メイ、ミョウ');
INSERT INTO all_kanji VALUES(838,'易','yasa, yasashii, yasui','やさ、やさしい、やすい','eki, i','エキ、イ');
INSERT INTO all_kanji VALUES(839,'皇','n/a','','kou, ou','コウ、オウ');
INSERT INTO all_kanji VALUES(840,'権','n/a','','ken, gon','ケン、ゴン');
INSERT INTO all_kanji VALUES(841,'神','kami, kan, kou','かみ、かん、こう','shin, jin','シン、ジン');
INSERT INTO all_kanji VALUES(842,'免','manuka, manukareru','まぬか、まぬかれる','men','メン');
INSERT INTO all_kanji VALUES(843,'逆','saka, sakasa, sakarau','さか、さかさ、さからう','gyaku','ギャク');
INSERT INTO all_kanji VALUES(844,'製','n/a','','sei','セイ');
INSERT INTO all_kanji VALUES(845,'偉','era, erai','えら、えらい','i','イ');
INSERT INTO all_kanji VALUES(846,'故','yue','ゆえ','ko','コ');
INSERT INTO all_kanji VALUES(847,'修','osa, osameru, osamaru','おさ、おさめる、おさまる','shuu, shu','シュウ、シュ');
INSERT INTO all_kanji VALUES(848,'早','haya, hayai, hayamaru, hayameru, hayaku','はや、はやい、はやまる、はやめる、はやく','sou','ソウ');
INSERT INTO all_kanji VALUES(849,'街','machi','まち','gai, kai','ガイ、カイ');
INSERT INTO all_kanji VALUES(850,'停','n/a','','tei','テイ');
INSERT INTO all_kanji VALUES(851,'路','ji','じ','ro','ロ');
INSERT INTO all_kanji VALUES(852,'章','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(853,'政','matsurigoto','まつりごと','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(854,'府','n/a','','fu','フ');
INSERT INTO all_kanji VALUES(855,'堅','kata, katai, katasa','かた、かたい、かたさ','ken','ケン');
INSERT INTO all_kanji VALUES(856,'担','katsu, katsugu, nina, ninau','かつ、かつぐ、にな、になう','tan','タン');
INSERT INTO all_kanji VALUES(857,'産','u, umu, umareru, ubu','う、うむ、うまれる、うぶ','san','サン');
INSERT INTO all_kanji VALUES(858,'省','kaeri, kaerimiru, habu, habuku','かえり、かえりみる、はぶ、はぶく','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(859,'昼','hiru','ひる','chuu','チュウ');
INSERT INTO all_kanji VALUES(860,'輪','wa','わ','rin','リン');
INSERT INTO all_kanji VALUES(861,'老','o, oiru, fu, fukeru','お、おいる、ふ、ふける','rou','ロウ');
INSERT INTO all_kanji VALUES(862,'荷','ni','に','ka','カ');
INSERT INTO all_kanji VALUES(863,'貧','mazu, mazushii, mazushisa','まず、まずしい、まずしさ','hin, bin','ヒン、ビン');
INSERT INTO all_kanji VALUES(864,'乏','tobo, toboshii, toboshisa','とぼ、とぼしい、とぼしさ','bou','ボウ');
INSERT INTO all_kanji VALUES(865,'記','shiru, shirusu','しる、しるす','ki','キ');
INSERT INTO all_kanji VALUES(866,'清','kiyo, kiyoi, kiyomaru, kiyomeru','きよ、きよい、きよまる、きよめる','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(867,'給','n/a','','kyuu','キュウ');
INSERT INTO all_kanji VALUES(868,'費','tsui, tsuiyasu','つい、ついやす','hi','ヒ');
INSERT INTO all_kanji VALUES(869,'刺','sa, sasu, sasaru, sashi','さ、さす、ささる、さし','shi','シ');
INSERT INTO all_kanji VALUES(870,'才','n/a','','sai','サイ');
INSERT INTO all_kanji VALUES(871,'紹','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(872,'介','n/a','','kai','カイ');
INSERT INTO all_kanji VALUES(873,'責','se, semeru','せ、せめる','seki','セキ');
INSERT INTO all_kanji VALUES(874,'誤','ayama, ayamaru, ayamari','あやま、あやまる、あやまり','go','ゴ');
INSERT INTO all_kanji VALUES(875,'益','n/a','','eki, yaku','エキ、ヤク');
INSERT INTO all_kanji VALUES(876,'毒','n/a','','doku','ドク');
INSERT INTO all_kanji VALUES(877,'骨','hone','ほね','kotsu','コツ');
INSERT INTO all_kanji VALUES(878,'健','suko, sukoyakana','すこ、すこやかな','ken','ケン');
INSERT INTO all_kanji VALUES(879,'康','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(880,'快','kokoroyo, kokoroyoi, kokoroyosa','こころよ、こころよい、こころよさ','kai','カイ');
INSERT INTO all_kanji VALUES(881,'本','moto','もと','hon','ホン');
INSERT INTO all_kanji VALUES(882,'積','tsu, tsumu, tsumoru, tsumori','つ、つむ、つもる、つもり','seki','セキ');
INSERT INTO all_kanji VALUES(883,'極','kiwa, kiwameru, kiwamaru, kiwamari, kiwami','きわ、きわめる、きわまる、きわまり、きわみ','kyoku, goku','キョク、ゴク');
INSERT INTO all_kanji VALUES(884,'哲','n/a','','tetsu','テツ');
INSERT INTO all_kanji VALUES(885,'公','ooyake','おおやけ','kou','コウ');
INSERT INTO all_kanji VALUES(886,'等','hito, hitoshii','ひと、ひとしい','tou','トウ');
INSERT INTO all_kanji VALUES(887,'節','fushi','ふし','setsu, sechi','セツ、セチ');
INSERT INTO all_kanji VALUES(888,'独','hito, hitori','ひと、ひとり','doku','ドク');
INSERT INTO all_kanji VALUES(889,'迎','muka, mukaeru','むか、むかえる','gei','ゲイ');
INSERT INTO all_kanji VALUES(890,'輸','n/a','','yu','ユ');
INSERT INTO all_kanji VALUES(891,'片','kata','かた','hen','ヘン');
INSERT INTO all_kanji VALUES(892,'冊','n/a','','satsu, saku','サツ、サク');
INSERT INTO all_kanji VALUES(893,'狭','sema, semai, seba, sebameru, sebamaru','せま、せまい、せば、せばめる、せばまる','kyou','キョウ');
INSERT INTO all_kanji VALUES(894,'差','sa, sasu, sashi','さ、さす、さし','sa','サ');
INSERT INTO all_kanji VALUES(895,'刷','su, suru','す、する','satsu','サツ');
INSERT INTO all_kanji VALUES(896,'利','ki, kiku, kiki','き、きく、きき','ri','リ');
INSERT INTO all_kanji VALUES(897,'拡','n/a','','kaku','カク');
INSERT INTO all_kanji VALUES(898,'陸','n/a','','riku','リク');
INSERT INTO all_kanji VALUES(899,'末','sue','すえ','matsu, batsu','マツ、バツ');
INSERT INTO all_kanji VALUES(900,'燃','mo, moeru, moyasu, mosu','も、もえる、もやす、もす','nen','ネン');
INSERT INTO all_kanji VALUES(901,'馬','uma, ma','うま、ま','ba','バ');
INSERT INTO all_kanji VALUES(902,'鹿','shika','しか','roku','ロク');
INSERT INTO all_kanji VALUES(903,'生','i, ikiru, u, umareru, umu, o, ha, haeru, hayasu, nama, ki','い、いきる、う、うまれる、うむ、お、は、はえる、はやす、なま、き','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(904,'枚','n/a','','mai','マイ');
INSERT INTO all_kanji VALUES(905,'負','ma, makeru, makasu, make, o, ou','ま、まける、まかす、まけ、お、おう','fu','フ');
INSERT INTO all_kanji VALUES(906,'渉','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(907,'卓','n/a','','taku','タク');
INSERT INTO all_kanji VALUES(908,'適','n/a','','teki','テキ');
INSERT INTO all_kanji VALUES(909,'創','n/a','','sou','ソウ');
INSERT INTO all_kanji VALUES(910,'精','n/a','','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(911,'認','mito, mitomeru','みと、みとめる','nin','ニン');
INSERT INTO all_kanji VALUES(912,'導','michibi, michibiku, michibiki','みちび、みちびく、みちびき','dou','ドウ');
INSERT INTO all_kanji VALUES(913,'固','kata, katameru, katamaru, katamari, katai','かた、かためる、かたまる、かたまり、かたい','ko','コ');
INSERT INTO all_kanji VALUES(914,'隣','tona, tonari','とな、となり','rin','リン');
INSERT INTO all_kanji VALUES(915,'台','n/a','','dai, tai','ダイ、タイ');
INSERT INTO all_kanji VALUES(916,'戦','ikusa, tataka, tatakau, tatakawasu','いくさ、たたか、たたかう、たたかわす','sen','セン');
INSERT INTO all_kanji VALUES(917,'和','yawa, yawaragu, yawarageru, nago, nagomu, nagoyaka','やわ、やわらぐ、やわらげる、なご、なごむ、なごやか','wa, o','ワ、オ');
INSERT INTO all_kanji VALUES(918,'忠','n/a','','chuu','チュウ');
INSERT INTO all_kanji VALUES(919,'混','ma, majiru, majiri, mazaru, mazeru','ま、まじる、まじり、まざる、まぜる','kon','コン');
INSERT INTO all_kanji VALUES(920,'鉄','n/a','','tetsu','テツ');
INSERT INTO all_kanji VALUES(921,'喫','n/a','','kitsu','キツ');
INSERT INTO all_kanji VALUES(922,'座','suwa, suwaru','すわ、すわる','za','ザ');
INSERT INTO all_kanji VALUES(923,'鼻','hana','はな','bi','ビ');
INSERT INTO all_kanji VALUES(924,'首','kubi','くび','shu','シュ');
INSERT INTO all_kanji VALUES(925,'震','furu, furueru, furue','ふる、ふるえる、ふるえ','shin','シン');
INSERT INTO all_kanji VALUES(926,'個','n/a','','ko, ka','コ、カ');
INSERT INTO all_kanji VALUES(927,'災','wazawa, wazawai','わざわ、わざわい','sai','サイ');
INSERT INTO all_kanji VALUES(928,'焦','ko, kogeru, kogasu, kogareru, ase, aseru, aseri','こ、こげる、こがす、こがれる、あせ、あせる、あせり','shou','ショウ');
INSERT INTO all_kanji VALUES(929,'破','yabu, yaburu, yabureru','やぶ、やぶる、やぶれる','ha','ハ');
INSERT INTO all_kanji VALUES(930,'壊','kowa, kowasu, kowareru','こわ、こわす、こわれる','kai','カイ');
INSERT INTO all_kanji VALUES(931,'造','tsuku, tsukuru, tukuri','つく、つくる、つくり','zou','ゾウ');
INSERT INTO all_kanji VALUES(932,'我','ware, wa','われ、わ','ga','ガ');
INSERT INTO all_kanji VALUES(933,'去','sa, saru','さ、さる','kyo, ko','キョ、コ');
INSERT INTO all_kanji VALUES(934,'巨','n/a','','kyo','キョ');
INSERT INTO all_kanji VALUES(935,'並','nami, na, naraberu, nara, narabu, narabini, narabi','なみ、な、ならべる、なら、ならぶ、ならびに、ならび','hei','ヘイ');
INSERT INTO all_kanji VALUES(936,'坂','saka','さか','han','ハン');
INSERT INTO all_kanji VALUES(937,'匹','hiki','ひき','hitsu','ヒツ');
INSERT INTO all_kanji VALUES(938,'緑','midori','みどり','ryoku, roku','リョク、ロク');
INSERT INTO all_kanji VALUES(939,'植','u, ueru, uwaru','う、うえる、うわる','shoku','ショク');
INSERT INTO all_kanji VALUES(940,'脈','n/a','','myaku','ミャク');
INSERT INTO all_kanji VALUES(941,'設','mou, moukeru','もう、もうける','setsu','セツ');
INSERT INTO all_kanji VALUES(942,'築','kizu, kizuku','きず、きずく','chiku','チク');
INSERT INTO all_kanji VALUES(943,'局','n/a','','kyoku','キョク');
INSERT INTO all_kanji VALUES(944,'温','atata, atataka, atatakai, atatamaru, atatameru','あたた、あたたか、あたたかい、あたたまる、あたためる','on','オン');
INSERT INTO all_kanji VALUES(945,'華','hana, hanayakana','はな、はなやかな','ka, ke','カ、ケ');
INSERT INTO all_kanji VALUES(946,'氏','uji','うじ','shi','シ');
INSERT INTO all_kanji VALUES(947,'算','n/a','','san','サン');
INSERT INTO all_kanji VALUES(948,'円','maru, marui','まる、まるい','en','エン');
INSERT INTO all_kanji VALUES(949,'邪','n/a','','ja','ジャ');
INSERT INTO all_kanji VALUES(950,'軽','karu, karui, karo, karoyakana','かる、かるい、かろ、かろやかな','kei','ケイ');
INSERT INTO all_kanji VALUES(951,'絡','kara, karamu, karamaru, karameru','から、からむ、からまる、からめる','raku','ラク');
INSERT INTO all_kanji VALUES(952,'毛','ke','け','mou','モウ');
INSERT INTO all_kanji VALUES(953,'布','nuno','ぬの','fu','フ');
INSERT INTO all_kanji VALUES(954,'仮','kari, karini','かり、かりに','ka, ke','カ、ケ');
INSERT INTO all_kanji VALUES(955,'狂','kuru, kuruu, kuruoshii, kuruwasu, kuruwaseru','くる、くるう、くるおしい、くるわす、くるわせる','kyou','キョウ');
INSERT INTO all_kanji VALUES(956,'障','sawa, sawaru','さわ、さわる','shou','ショウ');
INSERT INTO all_kanji VALUES(957,'害','n/a','','gai','ガイ');
INSERT INTO all_kanji VALUES(958,'演','n/a','','en','エン');
INSERT INTO all_kanji VALUES(959,'安','yasu, yasui, yasumaru, yasuraka','やす、やすい、やすまる、やすらか','an','アン');
INSERT INTO all_kanji VALUES(960,'劇','n/a','','geki','ゲキ');
INSERT INTO all_kanji VALUES(961,'葉','ha','は','you','ヨウ');
INSERT INTO all_kanji VALUES(962,'板','ita','いた','han, ban','ハン、バン');
INSERT INTO all_kanji VALUES(963,'階','n/a','','kai','カイ');
INSERT INTO all_kanji VALUES(964,'芝','shiba','しば','n/a','');
INSERT INTO all_kanji VALUES(965,'居','i, iru, o, oru','い、いる、お、おる','kyo','キョ');
INSERT INTO all_kanji VALUES(966,'移','utsu, utsusu, utsuru','うつ、うつす、うつる','i','イ');
INSERT INTO all_kanji VALUES(967,'努','tsuto, tsutomeru, tsutomete','つと、つとめる、つとめて','do','ド');
INSERT INTO all_kanji VALUES(968,'折','o, oru, ori, oreru','お、おる、おり、おれる','setsu','セツ');
INSERT INTO all_kanji VALUES(969,'欠','ka, kakeru, kaku, kakasu','か、かける、かく、かかす','ketsu','ケツ');
INSERT INTO all_kanji VALUES(970,'買','ka, kau','か、かう','bai','バイ');
INSERT INTO all_kanji VALUES(971,'皆','mina','みな','kai','カイ');
INSERT INTO all_kanji VALUES(972,'虫','mushi','むし','chuu','チュウ');
INSERT INTO all_kanji VALUES(973,'歯','ha','は','shi','シ');
INSERT INTO all_kanji VALUES(974,'圧','n/a','','atsu','アツ');
INSERT INTO all_kanji VALUES(975,'転','koro, korogaru, korogeru, korogasu, korobu','ころ、ころがる、ころげる、ころがす、ころぶ','ten','テン');
INSERT INTO all_kanji VALUES(976,'遺','n/a','','i, yui','イ、ユイ');
INSERT INTO all_kanji VALUES(977,'冗','n/a','','jou','ジョウ');
INSERT INTO all_kanji VALUES(978,'皮','kawa','かわ','hi','ヒ');
INSERT INTO all_kanji VALUES(979,'肉','n/a','','niku','ニク');
INSERT INTO all_kanji VALUES(980,'怪','aya, ayashii, ayashimu','あや、あやしい、あやしむ','kai, ke','カイ、ケ');
INSERT INTO all_kanji VALUES(981,'売','u, uru','う、うる','bai','バイ');
INSERT INTO all_kanji VALUES(982,'系','n/a','','kei','ケイ');
INSERT INTO all_kanji VALUES(983,'統','su, suberu, subete','す、すべる、すべて','tou','トウ');
INSERT INTO all_kanji VALUES(984,'鳥','tori','とり','chou','チョウ');
INSERT INTO all_kanji VALUES(985,'県','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(986,'尺','n/a','','shaku','シャク');
INSERT INTO all_kanji VALUES(987,'収','osa, osameru, osamaru','おさ、おさめる、おさまる','shuu','シュウ');
INSERT INTO all_kanji VALUES(988,'穫','n/a','','kaku','カク');
INSERT INTO all_kanji VALUES(989,'肥','ko, koe, koeru, koyasu, koyashi','こ、こえ、こえる、こやす、こやし','hi','ヒ');
INSERT INTO all_kanji VALUES(990,'草','kusa','くさ','sou','ソウ');
INSERT INTO all_kanji VALUES(991,'泳','oyo, oyogu, oyogi','およ、およぐ、およぎ','ei','エイ');
INSERT INTO all_kanji VALUES(992,'犬','inu','いぬ','ken','ケン');
INSERT INTO all_kanji VALUES(993,'亡','na, nai, naki, nakusu, nakunaru','な、ない、なき、なくす、なくなる','bou, mou','ボウ、モウ');
INSERT INTO all_kanji VALUES(994,'豊','yuta, yutaka','ゆた、ゆたか','hou','ホウ');
INSERT INTO all_kanji VALUES(995,'寮','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(996,'飽','a, akiru, akasu','あ、あきる、あかす','hou','ホウ');
INSERT INTO all_kanji VALUES(997,'油','abura','あぶら','yu','ユ');
INSERT INTO all_kanji VALUES(998,'菜','na','な','sai','サイ');
INSERT INTO all_kanji VALUES(999,'玉','tama','たま','gyoku','ギョク');
INSERT INTO all_kanji VALUES(1000,'減','he, heru, herasu','へ、へる、へらす','gen','ゲン');
INSERT INTO all_kanji VALUES(1001,'皿','sara','さら','n/a','');
INSERT INTO all_kanji VALUES(1002,'湯','yu','ゆ','tou','トウ');
INSERT INTO all_kanji VALUES(1003,'子','ko','こ','shi, su','シ、ス');
INSERT INTO all_kanji VALUES(1004,'除','nozo, nozoku','のぞ、のぞく','jo, ji','ジョ、ジ');
INSERT INTO all_kanji VALUES(1005,'控','hika, hikaeru, hikae','ひか、ひかえる、ひかえ','kou','コウ');
INSERT INTO all_kanji VALUES(1006,'蔵','kura','くら','zou','ゾウ');
INSERT INTO all_kanji VALUES(1007,'庫','n/a','','ko, ku','コ、ク');
INSERT INTO all_kanji VALUES(1008,'器','utsuwa','うつわ','ki','キ');
INSERT INTO all_kanji VALUES(1009,'凍','ko, kooru, kogo, kogoeru','こ、こおる、こご、こごえる','tou','トウ');
INSERT INTO all_kanji VALUES(1010,'聖','n/a','','sei','セイ');
INSERT INTO all_kanji VALUES(1011,'豚','buta','ぶた','ton','トン');
INSERT INTO all_kanji VALUES(1012,'絶','ta, taeru, tayasu, tatsu','た、たえる、たやす、たつ','zetsu','ゼツ');
INSERT INTO all_kanji VALUES(1013,'牧','maki','まき','boku','ボク');
INSERT INTO all_kanji VALUES(1014,'私','watashi, watakushi','わたし、わたくし','shi','シ');
INSERT INTO all_kanji VALUES(1015,'万','n/a','','man, ban','マン、バン');
INSERT INTO all_kanji VALUES(1016,'民','tami','たみ','min','ミン');
INSERT INTO all_kanji VALUES(1017,'誇','hoko, hokoru, hokori','ほこ、ほこる、ほこり','ko','コ');
INSERT INTO all_kanji VALUES(1018,'仏','hotoke','ほとけ','butsu','ブツ');
INSERT INTO all_kanji VALUES(1019,'殺','koro, korosu, koroshi','ころ、ころす、ころし','satsu, sai, setsu','サツ、サイ、セツ');
INSERT INTO all_kanji VALUES(1020,'含','fuku, fukumu, fukumi, fukumeru','ふく、ふくむ、ふくみ、ふくめる','gan','ガン');
INSERT INTO all_kanji VALUES(1021,'緊','n/a','','kin','キン');
INSERT INTO all_kanji VALUES(1022,'吸','su, suu','す、すう','kyuu','キュウ');
INSERT INTO all_kanji VALUES(1023,'筋','suji','すじ','kin','キン');
INSERT INTO all_kanji VALUES(1024,'奨','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(1025,'衛','n/a','','ei','エイ');
INSERT INTO all_kanji VALUES(1026,'語','kata, kataru','かた、かたる','go','ゴ');
INSERT INTO all_kanji VALUES(1027,'迷','mayo, mayou, mayoi','まよ、まよう、まよい','mei','メイ');
INSERT INTO all_kanji VALUES(1028,'充','a, ateru','あ、あてる','juu','ジュウ');
INSERT INTO all_kanji VALUES(1029,'礎','ishizue','いしずえ','so','ソ');
INSERT INTO all_kanji VALUES(1030,'標','n/a','','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(1031,'推','o, osu','お、おす','sui','スイ');
INSERT INTO all_kanji VALUES(1032,'到','ita, itaru','いた、いたる','tou','トウ');
INSERT INTO all_kanji VALUES(1033,'否','ina','いな','hi','ヒ');
INSERT INTO all_kanji VALUES(1034,'労','n/a','','rou','ロウ');
INSERT INTO all_kanji VALUES(1035,'範','n/a','','han','ハン');
INSERT INTO all_kanji VALUES(1036,'囲','kako, kakomu, kakou, kakoi','かこ、かこむ、かこう、かこい','i','イ');
INSERT INTO all_kanji VALUES(1037,'東','higashi','ひがし','tou','トウ');
INSERT INTO all_kanji VALUES(1038,'征','n/a','','sei','セイ');
INSERT INTO all_kanji VALUES(1039,'伏','fu, fuseru, fusu','ふ、ふせる、ふす','fuku','フク');
INSERT INTO all_kanji VALUES(1040,'抵','n/a','','tei','テイ');
INSERT INTO all_kanji VALUES(1041,'従','shitaga, shitagau, shitagaeru','したが、したがう、したがえる','juu, shou, ju','ジュウ、ショウ、ジュ');
INSERT INTO all_kanji VALUES(1042,'射','i, iru, sa, sasu','い、いる、さ、さす','sha','シャ');
INSERT INTO all_kanji VALUES(1043,'乱','mida, midareru, midasu, midare','みだ、みだれる、みだす、みだれ','ran','ラン');
INSERT INTO all_kanji VALUES(1044,'暴','aba, abaku, abareru','あば、あばく、あばれる','bou, baku','ボウ、バク');
INSERT INTO all_kanji VALUES(1045,'概','n/a','','gai','ガイ');
INSERT INTO all_kanji VALUES(1046,'焼','ya, yaku, yaki, yakeru','や、やく、やき、やける','shou','ショウ');
INSERT INTO all_kanji VALUES(1047,'編','a, amu, ami','あ、あむ、あみ','hen','ヘン');
INSERT INTO all_kanji VALUES(1048,'京','n/a','','kyou, kei, kin','キョウ、ケイ、キン');
INSERT INTO all_kanji VALUES(1049,'雲','kumo','くも','un','ウン');
INSERT INTO all_kanji VALUES(1050,'偏','katayo, katayoru, katayori','かたよ、かたよる、かたより','hen','ヘン');
INSERT INTO all_kanji VALUES(1051,'甘','ama, amai, amasa, amaeru, amae, amayakasu','あま、あまい、あまさ、あまえる、あまえ、あまやかす','kan','カン');
INSERT INTO all_kanji VALUES(1052,'衣','koromo','ころも','i','イ');
INSERT INTO all_kanji VALUES(1053,'騒','sawa, sawagu, sawagi, sawagasu, sawagashii','さわ、さわぐ、さわぎ、さわがす、さわがしい','sou','ソウ');
INSERT INTO all_kanji VALUES(1054,'悟','sato, satoru, satori','さと、さとる、さとり','go','ゴ');
INSERT INTO all_kanji VALUES(1055,'避','sa, sakeru','さ、さける','hi','ヒ');
INSERT INTO all_kanji VALUES(1056,'乾','kawa, kawaku, kawaki, kawakasu','かわ、かわく、かわき、かわかす','kan','カン');
INSERT INTO all_kanji VALUES(1057,'杯','sakazuki','さかずき','hai','ハイ');
INSERT INTO all_kanji VALUES(1058,'途','n/a','','to','ト');
INSERT INTO all_kanji VALUES(1059,'育','soda, sodatsu, sodateru','そだ、そだつ、そだてる','iku','イク');
INSERT INTO all_kanji VALUES(1060,'祈','ino, inoru, inori','いの、いのる、いのり','ki','キ');
INSERT INTO all_kanji VALUES(1061,'互','taga, tagai','たが、たがい','go','ゴ');
INSERT INTO all_kanji VALUES(1062,'賢','kashiko, kashikoi','かしこ、かしこい','ken','ケン');
INSERT INTO all_kanji VALUES(1063,'鳴','na, naku, naru, narasu','な、なく、なる、ならす','mei','メイ');
INSERT INTO all_kanji VALUES(1064,'純','n/a','','jun','ジュン');
INSERT INTO all_kanji VALUES(1065,'辛','kara, karai, karasa','から、からい、からさ','shin','シン');
INSERT INTO all_kanji VALUES(1066,'管','kuda','くだ','kan','カン');
INSERT INTO all_kanji VALUES(1067,'暗','kura, kurai, kurasa','くら、くらい、くらさ','an','アン');
INSERT INTO all_kanji VALUES(1068,'娘','musume','むすめ','n/a','');
INSERT INTO all_kanji VALUES(1069,'侮','anado, anadoru','あなど、あなどる','bu','ブ');
INSERT INTO all_kanji VALUES(1070,'住','su, sumu, sumai','す、すむ、すまい','juu','ジュウ');
INSERT INTO all_kanji VALUES(1071,'辱','hazukashi, hazukashime, hazukashimeru','はずかし、はずかしめ、はずかしめる','joku','ジョク');
INSERT INTO all_kanji VALUES(1072,'弾','hi, hiku, hiki, hazu, hazumu, tama','ひ、ひく、ひき、はず、はずむ、たま','dan','ダン');
INSERT INTO all_kanji VALUES(1073,'王','n/a','','ou','オウ');
INSERT INTO all_kanji VALUES(1074,'貝','kai','かい','n/a','');
INSERT INTO all_kanji VALUES(1075,'糸','ito','いと','shi','シ');
INSERT INTO all_kanji VALUES(1076,'竹','take','たけ','chiku','チク');
INSERT INTO all_kanji VALUES(1077,'林','hayashi','はやし','rin','リン');
INSERT INTO all_kanji VALUES(1078,'羽','ha, wa, hane','は、わ、はね','u','ウ');
INSERT INTO all_kanji VALUES(1079,'園','sono','その','en','エン');
INSERT INTO all_kanji VALUES(1080,'岩','iwa','いわ','gan','ガン');
INSERT INTO all_kanji VALUES(1081,'両','n/a','','ryou','リョウ');
INSERT INTO all_kanji VALUES(1082,'汽','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(1083,'弓','yumi','ゆみ','kyuu','キュウ');
INSERT INTO all_kanji VALUES(1084,'魚','uo, sakana','うお、さかな','gyo','ギョ');
INSERT INTO all_kanji VALUES(1085,'戸','to','と','ko','コ');
INSERT INTO all_kanji VALUES(1086,'黄','ki, ko','き、こ','kou, ou','コウ、オウ');
INSERT INTO all_kanji VALUES(1087,'谷','tani','たに','koku','コク');
INSERT INTO all_kanji VALUES(1088,'細','hosoi, hosoru, komakai, hoso, koma','ほそい、ほそる、こまかい、ほそ、こま','sai','サイ');
INSERT INTO all_kanji VALUES(1089,'矢','ya','や','shi','シ');
INSERT INTO all_kanji VALUES(1090,'寺','tera','てら','ji','ジ');
INSERT INTO all_kanji VALUES(1091,'星','hoshi','ほし','sei, shou','セイ、ショウ');
INSERT INTO all_kanji VALUES(1092,'親','oya, shita, shitashii','おや、した、したしい','shin','シン');
INSERT INTO all_kanji VALUES(1093,'船','fune, funa','ふね、ふな','sen','セン');
INSERT INTO all_kanji VALUES(1094,'池','ike','いけ','chi','チ');
INSERT INTO all_kanji VALUES(1095,'刀','katana','かたな','tou','トウ');
INSERT INTO all_kanji VALUES(1096,'麦','mugi','むぎ','baku','バク');
INSERT INTO all_kanji VALUES(1097,'米','kome','こめ','bei, mai','ベイ、マイ');
INSERT INTO all_kanji VALUES(1098,'里','sato','さと','ri','リ');
INSERT INTO all_kanji VALUES(1099,'委','n/a','','i','イ');
INSERT INTO all_kanji VALUES(1100,'央','n/a','','ou','オウ');
INSERT INTO all_kanji VALUES(1101,'宮','miya','みや','kyuu, guu, ku','キュウ、グウ、ク');
INSERT INTO all_kanji VALUES(1102,'区','n/a','','ku','ク');
INSERT INTO all_kanji VALUES(1103,'南','minami','みなみ','nan','ナン');
INSERT INTO all_kanji VALUES(1104,'血','chi','ち','ketsu','ケツ');
INSERT INTO all_kanji VALUES(1105,'湖','mizuumi','みずうみ','ko','コ');
INSERT INTO all_kanji VALUES(1106,'港','minato','みなと','kou','コウ');
INSERT INTO all_kanji VALUES(1107,'祭','matsuru, matsuri','まつる、まつり','sai','サイ');
INSERT INTO all_kanji VALUES(1108,'酒','sake, saka','さけ、さか','shu','シュ');
INSERT INTO all_kanji VALUES(1109,'昭','n/a','','shou','ショウ');
INSERT INTO all_kanji VALUES(1110,'勝','ka, katsu, kachi, masa, masaru','か、かつ、かち、まさ、まさる','shou','ショウ');
INSERT INTO all_kanji VALUES(1111,'整','totono, totonoeru, totonou','ととの、ととのえる、ととのう','sei','セイ');
INSERT INTO all_kanji VALUES(1112,'速','haya, sumi, hayai, hayameru, sumiyaka','はや、すみ、はやい、はやめる、すみやか','soku','ソク');
INSERT INTO all_kanji VALUES(1113,'炭','sumi','すみ','tan','タン');
INSERT INTO all_kanji VALUES(1114,'北','kita','きた','hoku','ホク');
INSERT INTO all_kanji VALUES(1115,'柱','hashira','はしら','chuu','チュウ');
INSERT INTO all_kanji VALUES(1116,'丁','n/a','','chou, tei','チョウ、テイ');
INSERT INTO all_kanji VALUES(1117,'帳','n/a','','chou','チョウ');
INSERT INTO all_kanji VALUES(1118,'笛','fue','ふえ','teki','テキ');
INSERT INTO all_kanji VALUES(1119,'投','na, nageru','な、なげる','tou','トウ');
INSERT INTO all_kanji VALUES(1120,'豆','mame','まめ','tou, zu','トウ、ズ');
INSERT INTO all_kanji VALUES(1121,'登','nobo, noboru','のぼ、のぼる','tou, to','トウ、ト');
INSERT INTO all_kanji VALUES(1122,'童','warabe','わらべ','dou','ドウ');
INSERT INTO all_kanji VALUES(1123,'波','nami','なみ','ha','ハ');
INSERT INTO all_kanji VALUES(1124,'箱','hako','はこ','n/a','');
INSERT INTO all_kanji VALUES(1125,'古','furu, furui','ふる、ふるい','ko','コ');
INSERT INTO all_kanji VALUES(1126,'西','nishi','にし','sei, sai','セイ、サイ');
INSERT INTO all_kanji VALUES(1127,'畑','hata, hatake','はた、はたけ','n/a','');
INSERT INTO all_kanji VALUES(1128,'筆','fude','ふで','hitsu','ヒツ');
INSERT INTO all_kanji VALUES(1129,'氷','koori, hi','こおり、ひ','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(1130,'羊','hitsuji','ひつじ','you','ヨウ');
INSERT INTO all_kanji VALUES(1131,'陽','hi','ひ','you','ヨウ');
INSERT INTO all_kanji VALUES(1132,'胃','n/a','','i','イ');
INSERT INTO all_kanji VALUES(1133,'栄','saka, sakaeru, ha, haeru','さか、さかえる、は、はえる','ei','エイ');
INSERT INTO all_kanji VALUES(1134,'塩','shio','しお','en','エン');
INSERT INTO all_kanji VALUES(1135,'億','n/a','','oku','オク');
INSERT INTO all_kanji VALUES(1136,'加','kuwa, kuwaeru, kuwawaru','くわ、くわえる、くわわる','ka','カ');
INSERT INTO all_kanji VALUES(1137,'漢','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(1138,'貨','n/a','','ka','カ');
INSERT INTO all_kanji VALUES(1139,'芽','me','め','ga','ガ');
INSERT INTO all_kanji VALUES(1140,'械','n/a','','kai','カイ');
INSERT INTO all_kanji VALUES(1141,'官','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(1142,'季','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(1143,'紀','n/a','','ki','キ');
INSERT INTO all_kanji VALUES(1144,'旗','hata','はた','ki','キ');
INSERT INTO all_kanji VALUES(1145,'救','suku, sukuu','すく、すくう','kyuu','キュウ');
INSERT INTO all_kanji VALUES(1146,'挙','a, ageru, agaru','あ、あげる、あがる','kyo','キョ');
INSERT INTO all_kanji VALUES(1147,'鏡','kagami','かがみ','kyou','キョウ');
INSERT INTO all_kanji VALUES(1148,'字','aza','あざ','ji','ジ');
INSERT INTO all_kanji VALUES(1149,'軍','n/a','','gun','グン');
INSERT INTO all_kanji VALUES(1150,'郡','n/a','','gun','グン');
INSERT INTO all_kanji VALUES(1151,'径','n/a','','kei','ケイ');
INSERT INTO all_kanji VALUES(1152,'候','sourou','そうろう','kou','コウ');
INSERT INTO all_kanji VALUES(1153,'航','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(1154,'札','fuda','ふだ','satsu','サツ');
INSERT INTO all_kanji VALUES(1155,'察','n/a','','satsu','サツ');
INSERT INTO all_kanji VALUES(1156,'士','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(1157,'史','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(1158,'司','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(1159,'好','kono, konomu, konomi, su, suki, suku, yo, yoi, i, ii','この、このむ、このみ、す、すき、すく、よ、よい、い、いい','kou','コウ');
INSERT INTO all_kanji VALUES(1160,'児','n/a','','ji, ni','ジ、ニ');
INSERT INTO all_kanji VALUES(1161,'辞','ya, yameru','や、やめる','ji','ジ');
INSERT INTO all_kanji VALUES(1162,'周','mawa, mawari','まわ、まわり','shuu','シュウ');
INSERT INTO all_kanji VALUES(1163,'順','n/a','','jun','ジュン');
INSERT INTO all_kanji VALUES(1164,'松','matsu','まつ','shou','ショウ');
INSERT INTO all_kanji VALUES(1165,'唱','tona, tonaeru','とな、となえる','shou','ショウ');
INSERT INTO all_kanji VALUES(1166,'照','te, teru, terasu, tereru','て、てる、てらす、てれる','shou','ショウ');
INSERT INTO all_kanji VALUES(1167,'臣','n/a','','shin, jin','シン、ジン');
INSERT INTO all_kanji VALUES(1168,'浅','asa, asai','あさ、あさい','sen','セン');
INSERT INTO all_kanji VALUES(1169,'倉','kura','くら','sou','ソウ');
INSERT INTO all_kanji VALUES(1170,'終','o, owari, owaraseru, owaru, oeru','お、おわり、おわらせる、おわる、おえる','shuu','シュウ');
INSERT INTO all_kanji VALUES(1171,'巣','su','す','sou','ソウ');
INSERT INTO all_kanji VALUES(1172,'孫','mago','まご','son','ソン');
INSERT INTO all_kanji VALUES(1173,'帯','o, obiru, obi','お、おびる、おび','tai','タイ');
INSERT INTO all_kanji VALUES(1174,'隊','n/a','','tai','タイ');
INSERT INTO all_kanji VALUES(1175,'仲','naka','なか','chuu','チュウ');
INSERT INTO all_kanji VALUES(1176,'貯','n/a','','cho','チョ');
INSERT INTO all_kanji VALUES(1177,'兆','kiza, kizasu, kizashi','きざ、きざす、きざし','chou','チョウ');
INSERT INTO all_kanji VALUES(1178,'腸','n/a','','chou','チョウ');
INSERT INTO all_kanji VALUES(1179,'底','soko','そこ','tei','テイ');
INSERT INTO all_kanji VALUES(1180,'典','n/a','','ten','テン');
INSERT INTO all_kanji VALUES(1181,'始','haji, hajimaru, hajimeru','はじ、はじまる、はじめる','shi','シ');
INSERT INTO all_kanji VALUES(1182,'灯','hi','ひ','tou','トウ');
INSERT INTO all_kanji VALUES(1183,'梅','ume','うめ','bai','バイ');
INSERT INTO all_kanji VALUES(1184,'博','n/a','','haku, baku','ハク、バク');
INSERT INTO all_kanji VALUES(1185,'票','n/a','','hyou','ヒョウ');
INSERT INTO all_kanji VALUES(1186,'夫','otto','おっと','fu, fuu','フ、フウ');
INSERT INTO all_kanji VALUES(1187,'付','tsu, tsukeru, tsuku, tsuki, zukeru, zuku','つ、つける、つく、つき、づける、づく','fu','フ');
INSERT INTO all_kanji VALUES(1188,'副','n/a','','fuku','フク');
INSERT INTO all_kanji VALUES(1189,'粉','ko, kona','こ、こな','fun','フン');
INSERT INTO all_kanji VALUES(1190,'兵','n/a','','hei, hyou','ヘイ、ヒョウ');
INSERT INTO all_kanji VALUES(1191,'包','tsutsu, tsutsumu, tsutsumi','つつ、つつむ、つつみ','hou','ホウ');
INSERT INTO all_kanji VALUES(1192,'大','oo, ookii','おお、おおきい','dai, tai','ダイ、タイ');
INSERT INTO all_kanji VALUES(1193,'浴','a, abiru, abiseru','あ、あびる、あびせる','yoku','ヨク');
INSERT INTO all_kanji VALUES(1194,'類','n/a','','rui','ルイ');
INSERT INTO all_kanji VALUES(1195,'例','tato, tatoeru','たと、たとえる','rei','レイ');
INSERT INTO all_kanji VALUES(1196,'歴','n/a','','reki','レキ');
INSERT INTO all_kanji VALUES(1197,'録','n/a','','roku','ロク');
INSERT INTO all_kanji VALUES(1198,'因','yoru, yo','よる、よ','in','イン');
INSERT INTO all_kanji VALUES(1199,'永','naga, nagai','なが、ながい','ei','エイ');
INSERT INTO all_kanji VALUES(1200,'液','n/a','','eki','エキ');
INSERT INTO all_kanji VALUES(1201,'往','n/a','','ou','オウ');
INSERT INTO all_kanji VALUES(1202,'桜','sakura','さくら','ou','オウ');
INSERT INTO all_kanji VALUES(1203,'四','yo, yon','よ、よん','shi','シ');
INSERT INTO all_kanji VALUES(1204,'恩','n/a','','on','オン');
INSERT INTO all_kanji VALUES(1205,'河','kawa','かわ','ka','カ');
INSERT INTO all_kanji VALUES(1206,'過','su, sugiru, sugosu, ayama, ayamatsu, ayamachi','す、すぎる、すごす、あやま、あやまつ、あやまち','ka','カ');
INSERT INTO all_kanji VALUES(1207,'賀','n/a','','ga','ガ');
INSERT INTO all_kanji VALUES(1208,'格','n/a','','kaku, kou','カク、コウ');
INSERT INTO all_kanji VALUES(1209,'額','hitai','ひたい','gaku','ガク');
INSERT INTO all_kanji VALUES(1210,'刊','n/a','','kan','カン');
INSERT INTO all_kanji VALUES(1211,'幹','miki','みき','kan','カン');
INSERT INTO all_kanji VALUES(1212,'眼','manako','まなこ','gan, gen','ガン、ゲン');
INSERT INTO all_kanji VALUES(1213,'久','hisa, hisashii, hisashiburi','ひさ、ひさしい、ひさしぶり','kyuu, ku','キュウ、ク');
INSERT INTO all_kanji VALUES(1214,'五','itsu, itsutsu','いつ、いつつ','go','ゴ');
INSERT INTO all_kanji VALUES(1215,'旧','n/a','','kyuu','キュウ');
INSERT INTO all_kanji VALUES(1216,'境','sakai','さかい','kyou, kei','キョウ、ケイ');
INSERT INTO all_kanji VALUES(1217,'均','n/a','','kin','キン');
INSERT INTO all_kanji VALUES(1218,'群','mu, mura, mureru, mure, muragaru','む、むら、むれる、むれ、むらがる','gun','グン');
INSERT INTO all_kanji VALUES(1219,'潔','isagiyo, isagiyoi','いさぎよ、いさぎよい','ketsu','ケツ');
INSERT INTO all_kanji VALUES(1220,'券','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(1221,'検','n/a','','ken','ケン');
INSERT INTO all_kanji VALUES(1222,'効','ki, kiku','き、きく','kou','コウ');
INSERT INTO all_kanji VALUES(1223,'鉱','n/a','','kou','コウ');
INSERT INTO all_kanji VALUES(1224,'妻','tsuma','つま','sai','サイ');
INSERT INTO all_kanji VALUES(1225,'六','mu, mui, muttsu','む、むい、むっつ','roku','ロク');
INSERT INTO all_kanji VALUES(1226,'秒','n/a','','byou','ビョウ');
INSERT INTO all_kanji VALUES(1227,'採','to, toru','と、とる','sai','サイ');
INSERT INTO all_kanji VALUES(1228,'財','n/a','','zai, sai','ザイ、サイ');
INSERT INTO all_kanji VALUES(1229,'罪','tsumi','つみ','zai','ザイ');
INSERT INTO all_kanji VALUES(1230,'雑','n/a','','zatsu, zou','ザツ、ゾウ');
INSERT INTO all_kanji VALUES(1231,'酸','su, sui','す、すい','san','サン');
INSERT INTO all_kanji VALUES(1232,'志','kokoroza, kokorozasu, kokorozashi','こころざ、こころざす、こころざし','shi','シ');
INSERT INTO all_kanji VALUES(1233,'師','n/a','','shi','シ');
INSERT INTO all_kanji VALUES(1234,'枝','eda','えだ','shi','シ');
INSERT INTO all_kanji VALUES(1235,'資','n/a','','shi','シ');
CREATE TABLE IF NOT EXISTS `kanjiID_session` (
	user_id INT NOT NULL, 
	kanji_data0 INT NOT NULL, 
	kanji_data1 INT NOT NULL, 
	kanji_data2 INT NOT NULL, 
	kanji_data3 INT NOT NULL, 
	kanji_data4 INT NOT NULL, 
	kanji_data5 INT NOT NULL, 
	kanji_data6 INT NOT NULL, 
	kanji_data7 INT NOT NULL, 
	kanji_data8 INT NOT NULL, 
	kanji_data9 INT NOT NULL, 
	PRIMARY KEY (user_id)
);
INSERT INTO kanjiID_session VALUES(1,285,41,147,1167,356,1018,89,288,317,223);
INSERT INTO kanjiID_session VALUES(3,549,848,583,1170,1213,287,344,57,19,1083);
INSERT INTO kanjiID_session VALUES(5,184,583,760,1215,117,1129,428,1032,1087,1069);
INSERT INTO kanjiID_session VALUES(6,435,140,1081,102,733,605,110,55,7,695);
INSERT INTO kanjiID_session VALUES(7,758,955,818,1089,568,785,265,148,1205,702);
INSERT INTO kanjiID_session VALUES(9,1138,523,1078,1152,58,1039,614,1155,1076,799);
CREATE TABLE review_table (
	user_id INT NOT NULL, 
	`review_kanjiID_json` VARCHAR(4096), 
	PRIMARY KEY (user_id)
);
INSERT INTO review_table VALUES(1,'[819, 468, 213, 340]');
INSERT INTO review_table VALUES(3,'[42, 1067, 1069, 561, 566, 567, 56, 1082, 59, 61, 1088, 1089, 67, 579, 1093, 70, 584, 1096, 73, 586, 77, 78, 79, 593, 82, 83, 1113, 1115, 605, 1118, 96, 98, 612, 1127, 1130, 619, 622, 111, 626, 1139, 1140, 1141, 1142, 1146, 125, 1150, 129, 1153, 1155, 132, 649, 651, 1165, 654, 655, 661, 155, 669, 671, 159, 1187, 675, 677, 166, 678, 1193, 686, 181, 182, 696, 1209, 1212, 703, 194, 706, 707, 197, 710, 195, 196, 1225, 1227, 213, 216, 217, 219, 751, 755, 758, 763, 254, 255, 771, 773, 262, 777, 266, 269, 781, 786, 788, 279, 795, 796, 288, 804, 808, 298, 299, 812, 302, 304, 817, 307, 312, 825, 313, 826, 829, 319, 322, 835, 331, 843, 334, 336, 852, 342, 346, 347, 348, 862, 351, 864, 357, 359, 885, 887, 889, 380, 897, 387, 904, 905, 908, 909, 914, 409, 926, 415, 421, 423, 935, 424, 431, 432, 945, 946, 433, 952, 953, 954, 442, 960, 961, 962, 450, 966, 978, 467, 468, 469, 470, 981, 986, 474, 987, 475, 477, 990, 993, 484, 487, 999, 492, 493, 1015, 1013, 503, 505, 506, 507]');
INSERT INTO review_table VALUES(5,'[1198, 878, 179, 1111]');
INSERT INTO review_table VALUES(6,'[]');
INSERT INTO review_table VALUES(7,'[256, 233, 714, 747, 784, 919, 1110, 1207, 667]');
INSERT INTO review_table VALUES(9,'[181, 120]');
CREATE TABLE IF NOT EXISTS `review_kanjiID_session` (
	user_id INT NOT NULL, 
	kanji_data0 INT, 
	kanji_data1 INT, 
	kanji_data2 INT, 
	kanji_data3 INT, 
	kanji_data4 INT, 
	kanji_data5 INT, 
	kanji_data6 INT, 
	kanji_data7 INT, 
	kanji_data8 INT, 
	kanji_data9 INT, 
	PRIMARY KEY (user_id)
);
INSERT INTO review_kanjiID_session VALUES(1,819,468,213,340,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO review_kanjiID_session VALUES(3,1118,678,255,804,432,334,1130,986,166,312);
INSERT INTO review_kanjiID_session VALUES(5,1198,1111,179,878,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO review_kanjiID_session VALUES(6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO review_kanjiID_session VALUES(7,747,256,667,919,1110,714,233,1207,784,NULL);
INSERT INTO review_kanjiID_session VALUES(9,120,181,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
